### ISSUE TITLE
Iceworks 安装依赖报错：write after end

### ISSUE THREAD

**Issue by TaoatGitHub** [alibaba/ice#1008]
## 环境信息

- 操作系统：Mac
- Iceworks 版本： Mojave 10.14

## 问题描述
安装包时报错

## 错误信息
TomdeMacBook-Pro% 正在清理 node_modules 目录请稍等...
清理 node_modules 目录完成
npm install --no-package-lock
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
events.js:183░░░░░░⸩ ⠴ extract:vm-browserify: sill extract request@2.88.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠴ extract:vm-browserify: sill extract request@2.88.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠙ extract:filesize: sill extract verror@1.10.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠹ extract:last-call-webpack-plugin: timing audit body Comp
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
npm WARN @icedesign/creative-login-scaffold@1.0.0 No repository field.
npm WARN @icedesign/creative-login-scaffold@1.0.0 No license field.

npm ERR! cancel after 1 retries!
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taozuo/.npm/_logs/2018-10-24T06_23_31_377Z-debug.log

TomdeMacBook-Pro%

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/47471610-976e6800-d83d-11e8-9971-7a76fc0a8be3.png)

科学上网

可以在设置面板切换为 cnpm 源，这块我们会尽快添加重试机制

**Comment by TaoatGitHub** [comment]
我这里确实已经科学上网过了，而且我用了两个源都试了，默认是taobao.org<http://taobao.org>，也同时试了npmjs.com<http://npmjs.com>

[cid:385E110D-00F6-488B-B964-6CEAF1B2D1DC]


不过还是感激你快速的回复

在 2018年10月25日，上午10:09，chenbin92 <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3995814%2F47471610-976e6800-d83d-11e8-9971-7a76fc0a8be3.png&data=02%7C01%7C%7C45a1b24f88584be1ebe108d63a1ee386%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636760301667197050&sdata=FuBqE9URFgSQJVIwWwz%2FD9sKtjMUqNXn8njz3aC37rQ%3D&reserved=0>

科学上网

可以在设置面板切换为 cnpm 源，这块我们会尽快添加重试机制

**Comment by Jayxiang** [comment]
一样的问题  都试了还是不行

**Comment by TaoatGitHub** [comment]
太好了  终于我不是特例了

在 2018年11月13日，下午2:18，Jayxiang <notifications@github.com<mailto:notifications@github.com>> 写道：


一样的问题 都试了还是不行

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/1045

**Comment by 1225358814** [comment]
同样构建失败 切换源 切换模版 全都是失败
npm install --no-package-lock
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flattedis its successor.
events.js:183░░░░░░⸩ ⠙ extract:cross-spawn: sill extract @vue/component-compile
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠙ extract:utils-merge: sill extract utils-merge@1.0.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠴ extract:parallel-transform: sill extract parallel-transf
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/eslint-8d8a44e7/lib/code-path-analysis/code-path-segment.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/eslint-8d8a44e7/lib/code-path-analysis/code-path-state.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/node-sass-0d9138a0/src/libsass/src/ast.hpp'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/wcwidth-7614ff18/combining.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/wcwidth-7614ff18/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/wcwidth-7614ff18/Readme.md'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/node-gyp-fdaff1e5/gyp/pylib/gyp/generator/ninja_test.py'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/node-gyp-fdaff1e5/gyp/pylib/gyp/generator/ninja.py'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/vue-89960b9c/dist/vue.esm.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/vue-template-es2015-compiler-3416615b/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/this/iceworks-workspace/qqqq/node_modules/.staging/vue-template-es2015-compiler-3416615b/README.md'
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! cancel after 1 retries!
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)

**Comment by lzx2005** [comment]
话说LZ，我用yarn构建成功了，你可以试一试，然后再用ice客户端启动项目就行了。

**Comment by TaoatGitHub** [comment]
给个教程把 不懂

在 2018年11月15日，下午4:38，Zhengxian Li <notifications@github.com<mailto:notifications@github.com>> 写道：


话说LZ，我用yarn构建成功了，你可以试一试，然后再用ice客户端启动项目就行了。

**Comment by lzx2005** [comment]
0. 安装好yarn组件
1. 进入工程目录
2. 执行
```
yarn install
```

3. 成功后回到ice GUI，点击“启动调试服务”

**Comment by Jayxiang** [comment]
> 1. 安装好yarn组件
> 2. 进入工程目录
> 3. 执行
> 
> ```
> yarn install
> ```
> 1. 成功后回到ice GUI，点击“启动调试服务”

确实好了  只能先这样了

**Comment by TaoatGitHub** [comment]
我的也好了，

首先下载了最新版本的飞冰for mac（我是11月15版本），
命令行brew install yarn
打开飞冰（重装最新版）
重装依赖

好了！

在 2018年11月15日，下午6:46，Jayxiang <notifications@github.com<mailto:notifications@github.com>> 写道：


  1.  安装好yarn组件
  2.  进入工程目录
  3.  执行

yarn install


  1.  成功后回到ice GUI，点击“启动调试服务”

确实好了 只能先这样了

**Comment by TaoatGitHub** [comment]
那你只能贴出来了  我这里一切正常 非常震撼

在 2018年11月16日，上午9:23，liter_on <notifications@github.com<mailto:notifications@github.com>> 写道：


然而yarn构建好项目依赖后 飞冰的其他功能运行还是都报错

**Comment by chenbin92** [comment]
请更新到 2.17.0 以上版本，添加了重试机制和支持使用 cnpm 源，建议默认设置 cnpm 源，能大幅降低失败率
