### ISSUE TITLE
Mac OS(10.12.6), 安装构建依赖失败， 对任意一个模板都如此。extract:platform:

### ISSUE THREAD

**Issue by scofield7419** [alibaba/ice#1045]
bash-3.2$ npm install --no-package-lock
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
**_events.js:183░░░░░░⸩ ⠼ extract:platform: sill extract find-up@2.1.0
      throw er; // Unhandled 'error' event
      ^_**

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠹ extract:p-limit: sill extract object.getownpropertydescr
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠙ extract:oauth-sign: sill extract punycode@1.4.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠹ extract:inherits: sill extract import-lazy@2.1.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠙ extract:debug: sill extract chalk@2.4.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
WARN tar ENOENT: no such file or directory, open '/Users/scofield/iceworks-workspace/template_1/node_modules/.staging/is-glob-7cd74568/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/scofield/iceworks-workspace/template_1/node_modules/.staging/is-glob-7cd74568/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/scofield/iceworks-workspace/template_1/node_modules/.staging/is-glob-7cd74568/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/scofield/iceworks-workspace/template_1/node_modules/.staging/is-glob-7cd74568/index.js'
npm WARN ice-koa-react-scaffold@1.0.0 No repository field.
npm WARN ice-koa-react-scaffold@1.0.0 No license field.
npm WARN The package koa-logger is included as both a dev and production dependency.

npm ERR! cancel after 1 retries!

bash-3.2$ npm start

> ice-koa-react-scaffold@1.0.0 start /Users/scofield/iceworks-workspace/template_1
> npm run client & npm run server

> ice-koa-react-scaffold@1.0.0 client /Users/scofield/iceworks-workspace/template_1
> ice dev --project-type=node

> ice-koa-react-scaffold@1.0.0 server /Users/scofield/iceworks-workspace/template_1
> nodemon server/app.js

sh: nodemon: command not found
sh: ice: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ice-koa-react-scaffold@1.0.0 server: `nodemon server/app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ice-koa-react-scaffold@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ice-koa-react-scaffold@1.0.0 start: `npm run client & npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ice-koa-react-scaffold@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by scofield7419** [comment]
注：
这个问题楼下有人提到过；
本机有梯子，但已切换为 cnpm 源；
有按照教程正确安装了Node.js 环境。


望解决！谢谢

**Comment by scofield7419** [comment]
第二次重启后，恢复了正常。

**Comment by Empireo** [comment]
@scofield7419 方便加下钉钉群吗，我这边提供个包帮你排查下问题
