### ISSUE TITLE
是否能够兼容网络条件不太好的情况

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#152]
系统 win7
node V8.9.3

- 初始化项目不成功，进度条走到十几左右提示timeout，重新执行创建项目，进度条直接到99，提示在安装依赖。
- 新建页面选择预览不成功，软件操作日志中提示有几个依赖包下载，timeout。
- 新建页面选择创建不成功

**Comment by mowatermelon** [comment]
但是很奇怪，同样的本地网络环境，对应的是lite模板，21个依赖包。

- 命令行安装项目依赖是可以的，一分钟下载完成。
- 但是在ice界面，图形操作就会提示timeout。

```bash
√ All packages installed (1192 packages installed from npm registry, used 1m, speed 36.22kB/s, json 1026(1.97MB), tarball 369.02kB)
```

> 所以到底是什么原因导致ice对于网络环境要求更高呢?

**Comment by noyobo** [comment]
网络的请求主要是在后去 模块，区块等信息，通过 g.alicdn.com 的域名。 通过网络上拦截了，建议开启这个域名的白名单。新建

关于依赖下载部分： 先确认下是否是 npm registry 是否一致

> 但是在ice界面，图形操作就会提示timeout。  

这个看下具体超时在什么模块上

**Comment by mowatermelon** [comment]
@noyobo  在创建失败的过程中，软件操作日志和node-cache的日志文件夹，都没有写入新日志，不知道操作到哪个版块了，我只知道，这个是进度条到二十多的情况下，直接提示 connect ETIMEDOUT 114.55.80.225:443，然后就没有其他信息产生了

**Comment by noyobo** [comment]
好的，这个我这边排查下。

**Comment by mowatermelon** [comment]
@noyobo   npm源的话，ice这边设置的是淘宝镜像，命令行的执行的也是`cnpm i`，是一致的镜像环境吧

**Comment by noyobo** [comment]
@mowatermelon 嗯。 一样的。iceworks 里用的是 npm，和 cnpm 还是有些不一样的。

**Comment by BeliefRC** [comment]
同样的问题 ，使用命令行安装依赖挺快的 。如果创建项目时，勾选上安装依赖，就会一直卡在99%。（都是使用的淘宝镜像）

**Comment by zteBill** [comment]
创建项目失败
ETIMEDOUT
Error: ETIMEDOUT
  at Timeout._onTimeout (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:849:19)
  at ontimeout (timers.js:475:11)
  at tryOnTimeout (timers.js:310:5)
  at Timer.listOnTimeout (timers.js:270:5)
@noyobo
