### ISSUE TITLE
订单管理系统模板，安装依赖总是失败

### ISSUE THREAD

**Issue by assmdx** [alibaba/ice#1610]
```
26819 warn @icedesign/order-management-scaffold@1.0.0 No repository field.
26820 warn @icedesign/order-management-scaffold@1.0.0 No license field.
26821 verbose stack Error: EPERM: operation not permitted, unlink 'F:\code\waibao\shengfayun\UI\webCompany\shengfa\node_modules\.staging\typescript-8847f591\lib\lib.dom.d.ts'
26822 verbose cwd F:\code\waibao\shengfayun\UI\webCompany\shengfa
26823 verbose Windows_NT 10.0.17134
26824 verbose argv "C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\app\\node_modules\\npm\\bin\\npm-cli.js" "install"
26825 verbose node v8.9.4
26826 verbose npm  v5.10.0
26827 error path F:\code\waibao\shengfayun\UI\webCompany\shengfa\node_modules\.staging\typescript-8847f591\lib\lib.dom.d.ts
26828 error code EPERM
26829 error errno -4048
26830 error syscall unlink
26831 error Error: EPERM: operation not permitted, unlink 'F:\code\waibao\shengfayun\UI\webCompany\shengfa\node_modules\.staging\typescript-8847f591\lib\lib.dom.d.ts'
26831 error  { Error: EPERM: operation not permitted, unlink 'F:\code\waibao\shengfayun\UI\webCompany\shengfa\node_modules\.staging\typescript-8847f591\lib\lib.dom.d.ts'
26831 error   cause:
26831 error    { Error: EPERM: operation not permitted, unlink 'F:\code\waibao\shengfayun\UI\webCompany\shengfa\node_modules\.staging\typescript-8847f591\lib\lib.dom.d.ts'
26831 error      errno: -4048,
26831 error      code: 'EPERM',
26831 error      syscall: 'unlink',
26831 error      path: 'F:\\code\\waibao\\shengfayun\\UI\\webCompany\\shengfa\\node_modules\\.staging\\typescript-8847f591\\lib\\lib.dom.d.ts' },
26831 error   stack: 'Error: EPERM: operation not permitted, unlink \'F:\\code\\waibao\\shengfayun\\UI\\webCompany\\shengfa\\node_modules\\.staging\\typescript-8847f591\\lib\\lib.dom.d.ts\'',
26831 error   errno: -4048,
26831 error   code: 'EPERM',
26831 error   syscall: 'unlink',
26831 error   path: 'F:\\code\\waibao\\shengfayun\\UI\\webCompany\\shengfa\\node_modules\\.staging\\typescript-8847f591\\lib\\lib.dom.d.ts',
26831 error   parent: '@icedesign/order-management-scaffold' }
26832 error The operation was rejected by your operating system.
26832 error It's possible that the file was already in use (by a text editor or antivirus),
26832 error or that you lack permissions to access it.
26832 error
26832 error If you believe this might be a permissions issue, please double-check the
26832 error permissions of the file and its containing directories, or try running
26832 error the command again as root/Administrator (though this is not recommended).
26833 verbose exit [ -4048, true ]

```

**Comment by assmdx** [comment]
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VA.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VC.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VE.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VG.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VI.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VN.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\VU.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\WF.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\WS.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\YE.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\YT.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\ZA.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\ZM.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\code\waibao\shengfayun\UI\web-company\shengfa\client\node_modules\.staging\caniuse-lite-52220cab\data\regions\ZW.js'

**Comment by assmdx** [comment]
npm ERR! code EINTEGRITY
npm ERR! sha1-ffjh6dBG1jHGUJ9+UxNX1K3CSqM= integrity checksum failed when using sha1: wanted sha1-ffjh6dBG1jHGUJ9+UxNX1K3CSqM= but got sha1-6A2qdpKhYKU3AT65DdCXva6bBL0=. (868240 bytes)

**Comment by assmdx** [comment]
verbose stack Error: sha1-FxssWvZsWelDEZkRejvK3Gb9z9Y= integrity checksum failed when using sha1: wanted sha1-FxssWvZsWelDEZkRejvK3Gb9z9Y= but got sha1-FTc4A+3DGrPZQlUnfrEuazYo11E=. (523372 bytes)
29666 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
29666 verbose stack     at emitNone (events.js:111:20)
29666 verbose stack     at Transform.emit (events.js:208:7)
29666 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
29666 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
29666 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
29667 verbose cwd F:\code\waibao\shengfayun\UI\web-company\shengfa\client
29668 verbose Windows_NT 10.0.17134
29669 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-package-lock"
29670 verbose node v8.11.2
29671 verbose npm  v5.6.0
29672 error code EINTEGRITY
29673 error sha1-FxssWvZsWelDEZkRejvK3Gb9z9Y= integrity checksum failed when using sha1: wanted sha1-FxssWvZsWelDEZkRejvK3Gb9z9Y= but got sha1-FTc4A+3DGrPZQlUnfrEuazYo11E=. (523372 bytes)

**Comment by assmdx** [comment]
应该是文件夹权限的问题，切换到桌面，新建文件夹，安装依赖即可解决
