### ISSUE TITLE
如何修改打包构建的目录？

### ISSUE THREAD

**Issue by dingyiming** [alibaba/ice#175]
如何修改打包构建的目录，以及hash 值等等， 目前构建出来的是这种目录

![](https://images-cdn.shimo.im/RvZCdnmAknI93nA4/image.png!thumbnail)

**Comment by noyobo** [comment]
与 https://github.com/alibaba/ice/issues/162 等同功能， webpack 配置化，该功能优先开发。

**Comment by noyobo** [comment]
修改路径，hash 配置示例

.webpackrc.js

```js
const { resolve } = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  output: {
    path: resolve('dist'),
    filename: '[name].[hash].js',
  },
  plugins: [
    new ExtractTextPlugin({
      filename: '[name].[hash].css',
      disable: false,
      allChunks: true,
    }),
  ],
};

```

**Comment by Restry** [comment]
@noyobo 请问 现在可以生成带hash命名的样式文件吗？ 按照你上面的代码打包报错。
如果不能生成hash命名的样式文件样式缓存会很麻烦。

**Comment by Restry** [comment]
下面的是报错内容， node : 11.0  npm: 6.4.1

`additional asset processing/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:115
      let moduleSource = chunkModule.source(compilation.dependencyTemplates, compilation.runtimeTemplate);
                                     ^

TypeError: chunkModule.source is not a function
    at Function.renderExtractedChunk (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:313:46)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:301:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/webpack/lib/Compilation.js:1278:32)
    at _err0 (eval at create (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at _async2.default.forEach.err (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:296:11)
    at /Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1064:13)
    at /Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:969:16
    at _async2.default.forEach.err (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:274:13)
    at /Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1064:13)
    at /Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:969:16
    at _async2.default.forEach (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:268:20)
    at /Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1069:9)
    at eachOf (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3172:5)
    at _async2.default.forEach (/Users/restry/Documents/temp/XTPhoto-Manager.test/node_modules/extract-text-webpack-plugin/dist/index.js:226:27)`

**Comment by Restry** [comment]
找到办法了， ice build的后面加上  --hash即可 ：）
