### ISSUE TITLE
[windows] 下 使用 ICE Design Pro 模板创建项目失败 

### ISSUE THREAD

**Issue by zteBill** [alibaba/ice#1758]
版本环境：
window7 64bit
Icework版本: 2.18.2
nodejs: V11.0.0

设置淘宝源： https://registry.npm.taobao.org

## 问题描述
1.使用ICE Design Pro 模版，创建项目
2.开始创建项目，创建项目文件失败

## 错误信息
Error: ETIMEDOUT
  at Timeout._onTimeout (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:849:19)
  at ontimeout (timers.js:475:11)
  at tryOnTimeout (timers.js:310:5)
  at Timer.listOnTimeout (timers.js:270:5)

## 备注

配置了淘宝源，IE设置了代理

**Comment by alvinhui** [comment]
应该是创建项目后“初始化项目”即安装依赖失败。

**Comment by chenbin92** [comment]
> Error: ETIMEDOUT

从错误信息看，是网络超时问题，考虑重试
