### ISSUE TITLE
window版本无法正常拉取包

### ISSUE THREAD

**Issue by wzl610** [alibaba/ice#1814]
## 问题描述
iceworks: 2.18.2
系统: windows7
node: 10.14.2

windows下载飞冰，模板市场下载模板，拉包的时候一直提示:

![image](https://user-images.githubusercontent.com/5937227/56117480-bb179d00-5f9a-11e9-8d28-90e920355caa.png)

做过以下尝试:
更改使用淘宝源，更改使用公司源(http)，自定义使用淘宝http源，关闭ssl，均无效。

同时还有一个很奇怪的地方，我自定义使用公司的源以后，在飞冰运行日志控制台查询npm源时候，为啥查询到的还是淘宝源(我本地npm设置的也是公司源)，如下图所示:

![image](https://user-images.githubusercontent.com/5937227/56117694-2d887d00-5f9b-11e9-8330-8adeb7ab82a3.png)

而且，相同的网络上，我自己的mac是可以正常使用淘宝源的。

**Comment by imsobear** [comment]
`unable to verify the first certificate` 问题参考这个文档： https://github.com/p2227/p2227.github.io/issues/5

**Comment by wzl610** [comment]
能好好看问题再关issue?能尝试成功的话还需要提issue做什么？

**Comment by TrumanDu** [comment]
安装iceworks3.0同样出该错误
```
C:\Windows\system32>iceworks
iceworks CLI: 3.1.0
{ RequestError: Error: unable to verify the first certificate
    at new RequestError (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  message: 'Error: unable to verify the first certificate',
  cause:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
       at TLSSocket.emit (events.js:189:13)
       at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  error:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
       at TLSSocket.emit (events.js:189:13)
       at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  options:
   { uri: 'https://registry.npm.taobao.org/iceworks',
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
WARN start warning Cannot find module 'C:\Users\hhhh\.iceworks-server\package.json'
>>> start downloading code C:\Users\td20\.iceworks-server

>>> ICEWORKS_CORE_VERSION: undefined

{ RequestError: Error: unable to verify the first certificate
    at new RequestError (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (d:\nvm\v10.15.2\node_modules\iceworks\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
  name: 'RequestError',
  message: 'Error: unable to verify the first certificate',
  cause:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
       at TLSSocket.emit (events.js:189:13)
       at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  error:
   { Error: unable to verify the first certificate
       at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
       at TLSSocket.emit (events.js:189:13)
       at TLSSocket._finishInit (_tls_wrap.js:633:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  options:
   { url: 'https://registry.npm.taobao.org/iceworks-server',
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```
