### ISSUE TITLE
不能下载模板

### ISSUE THREAD

**Issue by ypchen-chjs** [alibaba/ice#2004]
## 问题描述1
创建项目时，不能下载模板

## 错误信息1

ESOCKETTIMEDOUT

get-tarball-info-error: ESOCKETTIMEDOUT
  at ClientRequest. (D:\MyConfiguration\yiping.chen\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:816:19)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:106:13)
  at ClientRequest.emit (events.js:208:7)
  at TLSSocket.emitTimeout (_http_client.js:708:34)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:106:13)
  at TLSSocket.emit (events.js:208:7)
  at TLSSocket.Socket._onTimeout (net.js:407:8)
  at ontimeout (timers.js:475:11)
  at tryOnTimeout (timers.js:310:5)
  at Timer.listOnTimeout (timers.js:270:5)

**Comment by chenbin92** [comment]
`ESOCKETTIMEDOUT` 网络超时，在设置面板设置一下 cnpm 源

不要重复开一样的 issue https://github.com/alibaba/ice/issues/2005

**Comment by imsobear** [comment]
@ypchen-chjs 上午 taobao npm 源挂了几分钟，已经恢复了

**Comment by ypchen-chjs** [comment]
之后不再开重复issue
