### ISSUE TITLE
现有项目上增加区块出错

### ISSUE THREAD

**Issue by ypchen-chjs** [alibaba/ice#2005]
## 问题描述
现有项目上增加区块出错

## 错误信息
Error: get-tarball-info-error: 请求区块 tarball 包失败
  at w (D:\MyConfiguration\yiping.chen\AppData\Local\Programs\iceworks-desktop\resources\app\main\scaffolder\lib\utils.js:1:2174)
  at :null:null
  at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/2004
