### ISSUE TITLE
加入babel-plugin-import，无法正常build

### ISSUE THREAD

**Issue by leij1ang** [alibaba/ice#2008]
## 问题描述

按照文档说明加了babel-plugin-import插件,ice-scripts报错
```
const path = require('path');
module.exports = (context) => {
  const { webpack } = context;
  return {
    resolve: {
      alias: {
        'src': path.resolve(__dirname, 'src/'),
      },
    },
    plugins: [
      ['babel-plugin-import', {
        libraryName: '@alifd/next',
        style: true
      }]
    ]
  };
}

```

## 错误信息
```
ERR! ICE BUILD ERROR WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR! ICE BUILD ERROR  - configuration.plugins[11] should be one of these:
ERR! ICE BUILD ERROR    object { apply, … } | function
ERR! ICE BUILD ERROR    -> Plugin of type object or instanceof Function
ERR! ICE BUILD ERROR    Details:
ERR! ICE BUILD ERROR     * configuration.plugins[11] should be an object.
ERR! ICE BUILD ERROR       -> Plugin instance
ERR! ICE BUILD ERROR     * configuration.plugins[11] should be an instance of function
ERR! ICE BUILD ERROR       -> Function acting as plugin
ERR! ICE BUILD ERROR     at webpack (/Users/leijiang/Desktop/code/TI/node_modules/webpack/lib/webpack.js:31:9)
ERR! ICE BUILD ERROR     at Gulp.gulp.task (/Users/leijiang/Desktop/code/TI/node_modules/ice-scripts/lib/build.js:94:5)
ERR! ICE BUILD ERROR     at module.exports (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:34:7)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runTask (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:273:3)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runStep (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:214:10)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator.start (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:134:8)
ERR! ICE BUILD ERROR     at Gulp.gulp.task (/Users/leijiang/Desktop/code/TI/node_modules/ice-scripts/lib/build.js:85:10)
ERR! ICE BUILD ERROR     at module.exports (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:34:7)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runTask (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:273:3)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runStep (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:214:10)
ERR! ICE BUILD ERROR     at /Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:279:18
ERR! ICE BUILD ERROR     at finish (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:21:8)
ERR! ICE BUILD ERROR     at cb (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:29:3)
ERR! ICE BUILD ERROR     at next (/Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:75:7)
ERR! ICE BUILD ERROR     at CB (/Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:111:9)
ERR! ICE BUILD ERROR     at /Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:137:14
ERR! ICE BUILD ERROR     at FSReqWrap.oncomplete (fs.js:153:21)
ERR! ICE BUILD ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR! ICE BUILD ERROR  - configuration.plugins[11] should be one of these:
ERR! ICE BUILD ERROR    object { apply, … } | function
ERR! ICE BUILD ERROR    -> Plugin of type object or instanceof Function
ERR! ICE BUILD ERROR    Details:
ERR! ICE BUILD ERROR     * configuration.plugins[11] should be an object.
ERR! ICE BUILD ERROR       -> Plugin instance
ERR! ICE BUILD ERROR     * configuration.plugins[11] should be an instance of function
ERR! ICE BUILD ERROR       -> Function acting as plugin
ERR! ICE BUILD ERROR     at webpack (/Users/leijiang/Desktop/code/TI/node_modules/webpack/lib/webpack.js:31:9)
ERR! ICE BUILD ERROR     at Gulp.gulp.task (/Users/leijiang/Desktop/code/TI/node_modules/ice-scripts/lib/build.js:94:5)
ERR! ICE BUILD ERROR     at module.exports (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:34:7)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runTask (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:273:3)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runStep (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:214:10)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator.start (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:134:8)
ERR! ICE BUILD ERROR     at Gulp.gulp.task (/Users/leijiang/Desktop/code/TI/node_modules/ice-scripts/lib/build.js:85:10)
ERR! ICE BUILD ERROR     at module.exports (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:34:7)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runTask (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:273:3)
ERR! ICE BUILD ERROR     at Gulp.Orchestrator._runStep (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:214:10)
ERR! ICE BUILD ERROR     at /Users/leijiang/Desktop/code/TI/node_modules/orchestrator/index.js:279:18
ERR! ICE BUILD ERROR     at finish (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:21:8)
ERR! ICE BUILD ERROR     at cb (/Users/leijiang/Desktop/code/TI/node_modules/orchestrator/lib/runTask.js:29:3)
ERR! ICE BUILD ERROR     at next (/Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:75:7)
ERR! ICE BUILD ERROR     at CB (/Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:111:9)
ERR! ICE BUILD ERROR     at /Users/leijiang/Desktop/code/TI/node_modules/rimraf/rimraf.js:137:14
ERR! ICE BUILD ERROR     at FSReqWrap.oncomplete (fs.js:153:21)

```

**Comment by imsobear** [comment]
这里的 plugin 是 webpack 插件不是 babel 插件，bable 这个插件文档上有说怎么配置，先找找看，另外 next 按需构建是默认内置的，不需要手动配置。

**Comment by imsobear** [comment]
https://ice.work/docs/cli/basic/config#babelPluginImportConfig
