### ISSUE TITLE
iceworks cli 安装失败（3.0 beta 版本）

### ISSUE THREAD

**Issue by xierenyuan** [alibaba/ice#2403]
## 问题描述

使用 npm 安装 iceworks 失败

### 环境
```shell
系统: macos 10.14.5

node -v
v11.10.0

npm -v
6.7.0 
```

### 步骤 1

```shell
npm install iceworks -g
```

### 终端
```shell
> iceworks@3.0.0-beta.2 postinstall /Users/xierenhong/.nvm/versions/node/v11.10.0/lib/node_modules/iceworks
> node ./lib/downloadServer.js

[download successful]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for midway@^1.5.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'iceworks-server'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xierenhong/.npm/_logs/2019-07-10T07_58_58_505Z-debug.log
{ Error: Command failed: /bin/sh -c npm install
    at makeError (/Users/xierenhong/.nvm/versions/node/v11.10.0/lib/node_modules/iceworks/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/xierenhong/.nvm/versions/node/v11.10.0/lib/node_modules/iceworks/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: '/bin/sh -c npm install',
  timedOut: false,
  killed: false }
npm ERR! code ELIFECYCLE
```

### npm log
```shell
165 verbose argv "/Users/xierenhong/.nvm/versions/node/v11.10.0/bin/node" "/Users/xierenhong/.nvm/versions/node/v11.10.0/bin/npm" "install"
166 verbose node v11.10.0
167 verbose npm  v6.7.0
168 error code ETARGET
169 error notarget No matching version found for midway@^1.5.6
170 error notarget In most cases you or one of your dependencies are requesting
170 error notarget a package version that doesn't exist.
170 error notarget
170 error notarget It was specified as a dependency of 'iceworks-server'
171 verbose exit [ 1, true ]
```

看起来是缺少 midway

**Comment by chenbin92** [comment]
@xierenyuan 你的 npm 源是？

**Comment by xierenyuan** [comment]
- - 是因为源 是 registry = "https://registry.npm.alibaba-inc.com/" 吗？

**Comment by chenbin92** [comment]
> * * 是因为源 是 registry = "https://registry.npm.alibaba-inc.com/" 吗？

是的，Midway 内外网包不一致，内网没有这个包的

**Comment by xierenyuan** [comment]
@chenbin92  嗯 切换源 解决呢
