### ISSUE TITLE
终端构建项目失败  npm start   error !    iceworks  调试启动正常，但是build文件夹不实时更新

### ISSUE THREAD

**Issue by aLIEzsss4** [alibaba/ice#255]
```
ice-scripts 1.0.3
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'H:\icePro\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (H:\icePro\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (H:\icePro\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (H:\icePro\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (H:\icePro\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (H:\icePro\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (H:\icePro\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\icePro\node_modules\ice-scripts\lib\plugins\append-style-webpack-plugin.js:6:14)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/scaffold-pro@0.1.35 start: `ice dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @icedesign/scaffold-pro@0.1.35 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-\AppData\Roaming\npm-cache\_logs\2018-03-09T10_27_42_334Z-debug.log
```

build 里的版本会落后好几个，没办法重新构建，打包部署有难度

**Comment by aLIEzsss4** [comment]
npm debug log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @icedesign/scaffold-pro@0.1.35~prestart: @icedesign/scaffold-pro@0.1.35
6 silly lifecycle @icedesign/scaffold-pro@0.1.35~prestart: no script for prestart, continuing
7 info lifecycle @icedesign/scaffold-pro@0.1.35~start: @icedesign/scaffold-pro@0.1.35
8 verbose lifecycle @icedesign/scaffold-pro@0.1.35~start: unsafe-perm in lifecycle true
9 verbose lifecycle @icedesign/scaffold-pro@0.1.35~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;H:\icePro\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\software\WinSCP\;C:\Program Files (x86)\Yarn\bin;C:\software\Git\cmd;C:\software\Python35\Scripts\;C:\software\Python35\;C:\Users\-\AppData\Roaming\npm;C:\Users\-\AppData\Local\Yarn\bin;C:\Program Files (x86)\Microsoft VS Code\bin;H:\Fiddler
10 verbose lifecycle @icedesign/scaffold-pro@0.1.35~start: CWD: H:\icePro
11 silly lifecycle @icedesign/scaffold-pro@0.1.35~start: Args: [ '/d /s /c', 'ice dev' ]
12 silly lifecycle @icedesign/scaffold-pro@0.1.35~start: Returned: code: 1  signal: null
13 info lifecycle @icedesign/scaffold-pro@0.1.35~start: Failed to exec start script
14 verbose stack Error: @icedesign/scaffold-pro@0.1.35 start: `ice dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid @icedesign/scaffold-pro@0.1.35
16 verbose cwd H:\icePro
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @icedesign/scaffold-pro@0.1.35 start: `ice dev`
22 error Exit status 1
23 error Failed at the @icedesign/scaffold-pro@0.1.35 start script 'ice dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @icedesign/scaffold-pro package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ice dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs @icedesign/scaffold-pro
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls @icedesign/scaffold-pro
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by noyobo** [comment]
使用 iceworks 里的构建项目， 

命令行里的错误提示我优化下。

**Comment by noyobo** [comment]
在启动调试服务不会写入 build 目录文件夹，调试服务下的文件是现在内存里的。不是硬盘上的。

**Comment by noyobo** [comment]
终端构建增加 sass 检测

![image](https://user-images.githubusercontent.com/1292082/37382146-1fd6159e-277c-11e8-8093-28f9160505b6.png)

**Comment by noyobo** [comment]
ice-scripts 1.0.6 支持
