### ISSUE TITLE
依赖安装问题

### ISSUE THREAD

**Issue by lazytooo** [alibaba/ice#2550]
Error: 物料请求失败，地址: https://ice.alicdn.com/assets/base-components-1.x.json，错误：ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (file:///Applications/Iceworks.app/Contents/Resources/app/renderer/commons.js:27378:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:661:40)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)

Uncaught TypeError: Cannot read property 'isWrapped' of undefined
    at Linkifier._linkifyRow (Linkifier.ts:175)
    at Linkifier._linkifyRows (Linkifier.ts:83)
    at Linkifier.ts:74

**Comment by imsobear** [comment]
@lazytooo 建议升级到 iceworks 3.0 https://ice.work/docs/iceworks/migrate

**Comment by chenbin92** [comment]
@lazytooo 按照 @imsobear 的链接方式升级到 3.0，2.0 的版本不在继续维护。如果升级到 3.0 遇到问题可以重新打开 issue，我们这边会提供帮助
