### ISSUE TITLE
《快速开始》点击“运行”不成功

### ISSUE THREAD

**Issue by zhoux2016** [alibaba/ice#2591]
## 问题描述
我按照快速开始（https://ice.work/docs/iceworks/quick-start）
创建的项目，点击“运行”按钮，结果失败
使用模板：ICE  Design Pro
操作系统：win7
node：v12.7.0
npm：6.10.0
iceworks：3.0.1

输出的日志如下，请帮忙看下为什么无法运行

## 错误信息

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.0
3 info using node@v12.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @icedesign/pro-scaffold@3.0.5~prestart: @icedesign/pro-scaffold@3.0.5
6 info lifecycle @icedesign/pro-scaffold@3.0.5~start: @icedesign/pro-scaffold@3.0.5
7 verbose lifecycle @icedesign/pro-scaffold@3.0.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle @icedesign/pro-scaffold@3.0.5~start: PATH: C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\fast-search\node_modules\.bin;C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\iceworks\server\node_modules\.bin;C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\iceworks\server\.node\bin;C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\iceworks\server\node_modules\.bin;C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\.bin;C:\Program Files (x86)\Common Files\NetSarang;D:\app\Administrator\product\11.2.0\client_1\bin;C:\Program Files\Java\jdk1.8.0_66\bin;C:\Program Files\Java\jdk1.8.0_66\jre\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Java\apache-maven-3.5.0\bin;C:\Program Files\MySQL\MySQL Server 5.7.13\bin;C:\Python27\Scripts;C:\Python27;C:\Program Files\IDM Computer Solutions\UltraEdit;D:\Program Files\consul_1.5.2;D:\Program Files\curl-7.65.1\bin;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Administrator\AppData\Local\atom\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle @icedesign/pro-scaffold@3.0.5~start: CWD: C:\Users\Administrator\fast-search
10 silly lifecycle @icedesign/pro-scaffold@3.0.5~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'ice-scripts dev --port=8080 --https=false --analyzer=false --disabled-reload=true'
10 silly lifecycle ]
11 silly lifecycle @icedesign/pro-scaffold@3.0.5~start: Returned: code: 1  signal: null
12 info lifecycle @icedesign/pro-scaffold@3.0.5~start: Failed to exec start script
13 verbose stack Error: @icedesign/pro-scaffold@3.0.5 start: `ice-scripts dev --port=8080 --https=false --analyzer=false --disabled-reload=true`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\nvm\v12.7.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @icedesign/pro-scaffold@3.0.5
15 verbose cwd C:\Users\Administrator\fast-search
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.7.0
19 verbose npm  v6.10.0
20 error code ELIFECYCLE
21 error errno 1
22 error @icedesign/pro-scaffold@3.0.5 start: `ice-scripts dev --port=8080 --https=false --analyzer=false --disabled-reload=true`
22 error Exit status 1
23 error Failed at the @icedesign/pro-scaffold@3.0.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by zhoux2016** [comment]
ICE Design Pro failed
ICE Design Lite ok
![image](https://user-images.githubusercontent.com/16449365/62361079-dc51c880-b54c-11e9-8312-4926bab9bcc1.png)

**Comment by imsobear** [comment]
@zhoux2016 日志感觉不全呀，看不出来具体哪里报错了

**Comment by zhoux2016** [comment]
![image](https://user-images.githubusercontent.com/16449365/62434809-7b084000-b76c-11e9-8b82-132d8a4107c9.png)
[2019-08-05T02_32_21_414Z-debug.log](https://github.com/alibaba/ice/files/3465715/2019-08-05T02_32_21_414Z-debug.log)

**Comment by chenbin92** [comment]
1. 这边试了下模板能正常启动
2. 日志看起来还不是完整的，没有关键的报错信息进行排查，如果还有问题可以通过钉钉群联系进行排查
