### ISSUE TITLE
拖拽区块预览报错

### ISSUE THREAD

**Issue by zip01** [alibaba/ice#2828]
## 问题描述
在使用【元素拖拽放置】组件的过程中，发现无法拖拽，查看官方的例子也出现同样问题
官方例子预览： https://unpkg.com/@icedesign/dn-d-block@3.0.0/build/index.html
## 错误信息
控制台错误：
Uncaught Invariant Violation: Item must be an object.
    at Object.r [as default] (https://unpkg.com/@icedesign/dn-d-block@3.0.0/build/index.js:1:3035)
    at e.beginDrag (https://unpkg.com/@icedesign/dn-d-block@3.0.0/build/index.js:1:32622)
    at Object.beginDrag (https://unpkg.com/@icedesign/dn-d-block@3.0.0/build/index.js:31:47301)
    at e.handleTopDragStart (https://unpkg.com/@icedesign/dn-d-block@3.0.0/build/index.js:31:104044)

环境：
 "react": "^16.2.0",
  "react-dom": "^16.4.1",
"@alifd/next": "^1.x",

在其依赖组件react-dnd github issues中有同样问题：
https://github.com/react-dnd/react-dnd/issues/1051

**Comment by imsobear** [comment]
暂时先下线此区块，请按照 react-dnd 官方文档操作。
