### ISSUE TITLE
ice-scripts@1.0 启动异常，显示依赖的 sourceMap 抛异常了

### ISSUE THREAD

**Issue by gluo1130** [alibaba/ice#2864]
## 问题描述

ice1.0启动异常，根据控制台显示是source_map有关导致的

1、注释掉依赖包异常代码，项目可正常运行
2、升级ice-scripts 2.0，项目可启动，但是依赖且代码较多，暂无人力整改

望支持 多谢
## 错误信息
![image](https://user-images.githubusercontent.com/16134023/66796760-40c0d900-ef3b-11e9-9a90-f51716671ddb.png)

![image](https://user-images.githubusercontent.com/16134023/66796800-56360300-ef3b-11e9-924e-e9685c0d05ed.png)

异常堆栈：
```
throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":13,"column":1502},"source":"/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/@icedesign/base/lib/_components/@alife/next-button/lib/scss/mixin.scss","original":{"line":14,"column":-18},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-map-generator.js:298:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:351:13
    at SourceNode_walk [as walk] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_walk [as walk] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_walk [as walk] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/source-map/lib/source-node.js:342:8)
    at ConcatSource.proto.sourceAndMap (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:32)
    at OptimizeCssAssetsWebpackPlugin.processCss (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/optimize-css-assets-webpack-plugin/src/index.js:44:44)
    at Object.processor (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
    at each (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _next0 (eval at create (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:17)
    at _err0 (eval at create (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
    at compilation.hooks.optimizeChunkAssets.tapAsync (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/ice-scripts/lib/plugins/append-style-webpack-plugin.js:114:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/luogang05/Public/work/code/baidu/ebiz/cpdinf-jarvis-fe/node_modules/webpack/lib/Compilation.js:1309:36)
```
## 项目及环境有关配置
package.json
```
{
  "name": "jarvis",
  "version": "1.0.0",
  "description": "百度Jarvis项目",
  "homepage": "http://jarvis.baidu-int.com",
  "dependencies": {
    "@alifd/next": "^1.17.11",
    "@antv/data-set": "^0.8.5",
    "@icedesign/card": "^0.1.2",
    "@icedesign/container": "^0.1.2",
    "@icedesign/data-binder": "^0.1.1",
    "@icedesign/form-binder": "^0.1.4",
    "@icedesign/icon": "^0.1.1",
    "@icedesign/img": "^0.1.1",
    "@icedesign/layout": "^0.1.0",
    "@icedesign/menu": "^0.1.0",
    "@icedesign/notification": "1.0.0",
    "@icedesign/skin": "^0.1.0",
    "antd": "^3.13.0",
    "axios": "^0.17.1",
    "bizcharts": "3.1.0",
    "classnames": "^2.2.5",
    "copy-to-clipboard": "^3.0.8",
    "d3": "^4.10.0",
    "enquire-js": "^0.1.3",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "foundation-symbol": "^0.1.0",
    "i": "^0.3.6",
    "immutable": "^3.8.2",
    "is-hotkey": "^0.1.1",
    "json-loader": "^0.5.7",
    "moment": "^2.24.0",
    "node": "8.12.0",
    "prop-types": "^15.6.1",
    "react": "^16.8.4",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.0.0",
    "react-markdown": "^4.0.3",
    "react-redux": "^5.0.7",
    "react-router": "^3.2.1",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "slate": "^0.32.5",
    "slate-plain-serializer": "^0.5.6",
    "slate-react": "^0.11.6"
  },
  "devDependencies": {
    "@icedesign/base": "^0.2.6",
    "@icedesign/label": "^0.1.2",
    "@icedesign/panel": "^0.1.2",
    "@icedesign/title": "^0.1.1",
    "babel-core": "6.26.3",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^8.0.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.28.11",
    "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.11",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "ice-scripts": "^1.1.1",
    "install": "^0.12.2",
    "js-cookie": "^2.2.0",
    "mockjs": "^1.0.1-beta3",
    "node-sass": "^4.9.0",
    "npm": "^6.9.0",
    "react-ace": "^6.1.1",
    "react-loadable": "^5.5.0",
    "sass-loader": "^7.0.1",
    "style-loader": "^0.21.0",
    "stylus-loader": "^3.0.2",
    "url-loader": "^1.1.2"
  },
  "scripts": {
    "start": "ice dev",
    "build": "ice build",
    "lint": "eslint . --ext '.js,.jsx' --fix"
  },
  "publishConfig": {
    "registry": "http://npm.baidu-int.com/",
    "access": "public"
  },
  "buildConfig": {
    "theme": "@icedesign/skin",
    "entry": "src/index.js"
  },
  "scaffoldConfig": {
    "name": "Jarvis",
    "title": "Jarvis"
  },
  "title": "Jarvis"
}

```
.webpackrc.js

```
const proxyTarget = "http://jarvis.baidu-int.com:8057";
const { resolve } = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
module.exports = {
    resolve: {
        alias: {
            '~': resolve(__dirname, 'src/')
        }
    },
    devServer: {
        proxy: {
            '/test': {
                target: proxyTarget,
                changeOrigin: true,
                pathRewrite: { "^/test": "" },
                bypass: function (req, res, proxyOpt) {
                    // 添加 HTTP Header 标识 proxy 开启
                    res.set('X-ICE-PROXY', 'on');
                    res.set('X-ICE-PROXY-BY', proxyTarget);
                }
            },
        }
    },
    output: {
        filename: 'js/[name][hash].js'
    },
    // query: {
    //     presets: ['react', 'es2015', 'stage-0']
    // },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    "css-loader"
                ]
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: 'css/[name][hash].css',
            chunkFilename: '[id].css'
        }),
        new OptimizeCSSAssetsPlugin({
            assetNameRegExp: /\.css$/g,
            cssProcessor: require('cssnano'),
            // cssProcessorOptions: cssnanoOptions,
            cssProcessorPluginOptions: {
                preset: ['default', {
                    discardComments: {
                        removeAll: true,
                    },
                    normalizeUnicode: false
                }]
            },
            canPrint: true
        })
    ]
};
```

其他信息
```
node: v10.9.0
npm: 6.2.0
mac: 10.15 (19A583)

```

**Comment by gluo1130** [comment]
暂时将版本改成 "ice-scripts": "1.9.1"  使用了

**Comment by imsobear** [comment]
1. 建议升级 2.0
2. 注释掉依赖包异常代码，具体的异常代码是什么？

**Comment by gluo1130** [comment]
2、
![image](https://user-images.githubusercontent.com/16134023/66808148-344d7800-ef5d-11e9-9e13-d01c5149c508.png)

```
throw new Error('Invalid mapping: ' + JSON.stringify({
        generated: aGenerated,
        source: aSource,
        original: aOriginal,
        name: aName
      }));
```

注释抛异常处理部分代码可以运行  （source-map/lib/source-map-generator.js）

如上异常堆栈所述

这个和修复无关，建议还是处理下这个ice依赖导致的异常

我暂时将ice-scripts降版本使用了 （1.10.2 - 1.9.1）

**Comment by ClarkXia** [comment]
@gluo1130 这个问题是否可以提供个最小复现的项目 demo

**Comment by gluo1130** [comment]
> @gluo1130 这个问题是否可以提供个最小复现的项目 demo

删除项目主要代码后，保持package不变，尝试运行了一下，未复现，所以原型demo暂无法提供。原有代码npm包删除后重新install后会有相应问题。我先再关注一下吧，有问题再寻求你们的帮助，多谢。
