### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by forrestneo** [alibaba/ice#2897]
iceworks CLI: 3.1.3
iceworks Core: 3.4.0 C:\Users\Administrator\.iceworks-server

报错信息如下图：

**Comment by forrestneo** [comment]
图

**Comment by forrestneo** [comment]
stack     at Array.<anonymous> (G:\node.js\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
npm verb stack     at LOOP (G:\node.js\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
npm verb stack     at chain (G:\node.js\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
npm verb stack     at G:\node.js\node_modules\npm\lib\install\deps.js:404:5
npm
 verb stack     at cb (G:\node.js\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
npm verb stack     at G:\node.js\node_modules\npm\lib\install\deps.js:459:21

npm verb cwd C:\Users\Administrator\Desktop\node.js\analysesystem\admin

npm verb
 Windows_NT 10.0.18362

npm verb argv "G:\\node.js\\node.exe" "G:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "--loglevel" "silly"
npm verb node v12.13.0
npm verb npm  v6.12.0

npm ERR!
 Unexpected end of JSON input while parsing near '...GMWSLJXFbJsp5OzDpeTwJ'

npm 
verb exit [ 1, true ]

npm 
timing npm Completed in 52891ms


npm
 ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-11-01T13_43_20_551Z-debug.log

**Comment by forrestneo** [comment]
更新npm的半步问题之后已解决
