### ISSUE TITLE
启动服务报错

### ISSUE THREAD

**Issue by forrestneo** [alibaba/ice#2899]
日志如下：

```bash
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\node.js\analysesystem\admin\node_modules\ice-scripts\bin\ice-scripts.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

npm ERR! code ELIFECYCLE
npm ERR! errno
 1

npm ERR! @icedesign/admin-scaffold@3.0.0 start: `ice-scripts dev --https=true --analyzer=true --disabled-reload=true`
npm ERR! Exit status 1
npm ERR!
 
npm ERR! Failed at the @icedesign/admin-scaffold@3.0.0 start script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-11-02T06_39_22_403Z-debug.log

Task has stopped
```

**Comment by imsobear** [comment]
感觉是依赖没装好，重新安装下依赖试试呢？
