### ISSUE TITLE
Got error of getEnv(), can not install deps or run task.

### ISSUE THREAD

**Issue by aixfox** [alibaba/ice#2960]
### envs
iceworks: 3.1.9
shell: WSL ubuntu 18.04 zsh
node: 12.11.1
npm: 6.12.0

### steps

```
1. npm i -g iceworks

2. iceworks

3. init a project with scaffold "ice pro"

4. (re)install dependencies of project
    or run task (after installing dependencies manually)
```

## 错误信息

shell console log:
```
ERROR 1772 adapter[dependency][reset] got error: TypeError: Cannot read property 'split' of undefined
    at Project.getEnv (/home/h/.iceworks-server/dist/lib/plugin/project-manager/app.js:73:41)
    at Dependency.reset (/home/h/.iceworks-server/dist/lib/adapter/modules/dependency/index.js:152:31)
    at async /home/h/.iceworks-server/dist/app/io/middleware/adapter.js:15:32
    at async session (/home/h/.iceworks-server/node_modules/koa-session/index.js:41:7)
```

## 修复建议

```javascript
// .iceworks-server/dist/lib/plugin/project-manager/app.js:73
const envPath = shellPath.sync().split(path.delimiter);
```

```javascript
// https://github.com/sindresorhus/shell-path/blob/master/index.js#L5
// getEnv()
module.exports.sync = () => shellEnv.sync().PATH;
```

其中 `shell-path@2.1.0` 依赖 `shell-env@0.3.0`，`require('shell-env').sync()` 返回为 `{ '': '' }`。
试了一下最新的 `shell-env@3.0.0` 可以正确取到 PATH。

getEnv() 挂了啥也做不了。

`shell-path` 很久没更新了，也很简单，直接使用 `shell-env` 吧。

**Comment by alvinhui** [comment]
看起来是 PATH 变量为 undefined。

- 直接使用 `shell-env`；
- 加了一个更严谨的判断。

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/2964
