### ISSUE TITLE
新加的私有模板物料找不到

### ISSUE THREAD

**Issue by wangyuks** [alibaba/ice#3012]
## 问题描述
我新加了一个私有模板物料，想通过项目去下载，以下是我配置的物料信息：
repository: "https://gitlab.XXX.com/cloud-platform-XXX/polyhedron-head-materiel/tree/master/scaffolds/ice-landing-homepage",
 source: {
     type: "npm",
     npm: "@icedesign/landing-homepage-scaffold",
     version: "1.0.0",
     registry: "http://registry.XXX.com/"
 }

## 错误信息

2020-01-09 11:28:38,063 ERROR 364800 nodejs.PackageNotFoundError: Package `@icedesign/landing-homepage-scaffold` could not be found
    at AsyncFunction.packageJson [as default] (D:\XXX\packages\iceworks-server\node_modules\package-json\index.js:74:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
name: "PackageNotFoundError"
pid: 364800
hostname: XXX

**Comment by imsobear** [comment]
怀疑是你的私有 npm 没同步 `@icedesign` 这个 scope 下的包

**Comment by imsobear** [comment]
没有回复，先关闭了，有问题再打开下。
