### ISSUE TITLE
使用icejs内置的store报错

### ISSUE THREAD

**Issue by HateTomatoes** [alibaba/ice#3249]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
**编辑报错，如下所示**
```
emittingError: Cyclic dependency
    at visit (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/toposort/index.js:35:13)
    at visit (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/toposort/index.js:53:9)
    at visit (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/html-webpack-plugin/index.js:364:35)
    at /Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/webpack/lib/Compiler.js:367:19)
    at onCompiled (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/webpack/lib/Compiler.js:553:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pyramids/Documents/WorkSpace/react/vendornoscreensale/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/pro-scaffold@1.4.1 start: `icejs start --port=4448 --mode debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @icedesign/pro-scaffold@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pyramids/.npm/_logs/2020-05-29T10_37_23_271Z-debug.log

```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.4.1
* Node verson：v10.16.3
* Platform：MacOS Google Chrome 81.0.4044.138
* `build.json`：
```
{
  "plugins": [
    "./build.plugin.js",
    ["build-plugin-antd", {
      "themeConfig": {
        "brand-primary": "#1DA57A"
      },
      "importOptions": {
        "libraryName": "antd-mobile",
        "libraryDirectory": "es",
        "style": true
      }
    }]
  ],
  "proxy": {
    "/file": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/api": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/webapi": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/test": {
      "enable": true,
      "target": "http://localhost:3200"
    }
  },
  "alias": {
    "@utils": "./src/utils/",
    "@components": "./src/components/",
    "@src": "./src/"
  }
}
```
* `src/app.(ts|js)`：
```
import React from "react";
import {createApp, config} from 'ice';
import VConsole from 'vconsole';
import {Provider} from 'react-redux';
import {createBrowserHistory} from 'history';
import configureStore from "./configureStore";
import PageLoading from './components/PageLoading';

require('./config/netConfig');
import './global.css';
// import 'antd-mobile/dist/antd-mobile.css'; // or 'antd-mobile/dist/antd-mobile.less'

console.log('dddd=>', IS_DEBUG);
if(IS_DEBUG){
    var vconsole = new VConsole();
}

// 注意事件冲突
document.body.addEventListener('touchstart', function () { });

// rem适配
const idealViewWidth = window.screen.width;
const BASICVALUE = 1080;
document.documentElement.style.fontSize = `${(idealViewWidth / BASICVALUE) * 100}px`;

// const history = createBrowserHistory();
// const store = configureStore({}, history);

const appConfig = {
    app: {
        // 可选，是否解析路由组件的查询参数
        parseSearchParams: true,
        // 可选，自定义添加 Provider
        // addProvider: ({children}) => {
        //     return (
        //         <Provider store={store}>
        //             {children}
        //         </Provider>
        //     );
        // },
    },
    router: {
        type: 'browser', // 配置 browser 路由
        fallback: <PageLoading />,
        modifyRoutes: (routes) => {
            console.log('routes = ', routes);
            return routes;
        }
    },
};

createApp(appConfig);
```

**What is the expected behavior?**
正常编译

**Comment by chenbin92** [comment]
> configureStore

上面的代码看不出来问题，提供一个最小可复现的 demo

**Comment by chenbin92** [comment]
@HateTomatoes 请提供一个可复现的 demo 然后在重新打开该 issue

**Comment by HateTomatoes** [comment]
@chenbin92 今天抽空写了下demo，发现更新到1.5.0版本就没问题了。
