### ISSUE TITLE
ERR! iceworks sync error Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by brizer** [alibaba/ice#3267]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：latest
* Node verson：8.9.1
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
``` sh
iceworks sync
```

ERR! iceworks sync error Parameter "url" must be a string, not undefined

The content of my materials.json is:

``` json

{
  "template": "@icedesign/ice-vue-material-template",
  "type": "vue",
  "name": "my-ice-materials",
  "description": "This is a ice material project",
  "author": "",
  "blocks": [
    {
      "name": "ExampleBlock",
      "title": "demo block",
      "category": "Information",
      "description": "intro block",
      "homepage": "https://unpkg.com/example-block2@0.1.0/build/index.html",
      "categories": [
        "Information"
      ],
      "source": {
        "type": "npm",
        "npm": "example-block2",
        "version": "0.1.0",
        "registry": "https://registry.npmjs.org"
      },
      "dependencies": {
        "vue": "^2.5.16"
      },
      "screenshot": "https://unpkg.com/example-block2@0.1.0/screenshot.png",
      "screenshots": [
        "https://unpkg.com/example-block2@0.1.0/screenshot.png"
      ],
      "publishTime": "2020-06-09T11:58:03.500Z",
      "updateTime": "2020-06-09T11:58:05.775Z"
    }
  ],
  "components": [
    {
      "name": "button",
      "title": "基础按钮",
      "description": "",
      "homepage": "https://unpkg.com/ice-my-btn@1.0.0/build/index.html",
      "categories": [],
      "category": "",
      "repository": {
        "type": "git"
      },
      "source": {
        "type": "npm",
        "npm": "ice-my-btn",
        "version": "1.0.0",
        "registry": "https://registry.npmjs.org",
        "author": "brizer"
      },
      "dependencies": {
        "vue": "^2.5.16"
      },
      "screenshot": "",
      "screenshots": "",
      "publishTime": "2020-06-09T12:14:07.969Z",
      "updateTime": "2020-06-09T12:14:10.324Z"
    }
  ],
  "scaffolds": []
}

```

[This Project](https://github.com/FunnyLiu/my-ice-materials) can reproduce this error.

**Comment by imsobear** [comment]
@brizer `LOG_LEVEL iceworks sync` 然后把完整的日志贴出来

**Comment by brizer** [comment]
能描述详细点吗，朋友第一次用。这里的LOG_LEVEL需要指定什么，或者需要什么库？

**Comment by imsobear** [comment]
写错了，`LOG_LEVEL=verbose iceworks sync` 通过环境变量 `LOG_LEVEL` 输出调试日志，windows 系统的话设置环境变量需要结合 cross-env：

```bash
$ npm i -g cross-env
$ cross-env LOG_LEVEL=verbose iceworks sync
```

**Comment by brizer** [comment]
> `LOG_LEVEL=verbose iceworks sync`

感谢，朋友，日志如下：

``` sh
LOG_LEVEL=verbose iceworks sync 
iceworks CLI: 3.2.2
verb checkAliInternal error:  Error: ETIMEDOUT
verb config.get success fusion-token 8dced53e520b48e398fa0deb28f555f9
verb get fusion token success 8dced53e520b48e398fa0deb28f555f9
verb fetch fusion sites start { method: 'GET',
verb fetch fusion sites start   uri: 'https://fusion.design/api/v1/mysites',
verb fetch fusion sites start   headers: { 'x-auth-token': '8dced53e520b48e398fa0deb28f555f9' },
verb fetch fusion sites start   json: true,
verb fetch fusion sites start   followRedirect: false }
ERR! iceworks sync error Parameter "url" must be a string, not undefined
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at dispatchHttpRequest (/usr/local/lib/node_modules/iceworks/node_modules/axios/lib/adapters/http.js:57:22)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/local/lib/node_modules/iceworks/node_modules/axios/lib/adapters/http.js:18:10)
    at dispatchRequest (/usr/local/lib/node_modules/iceworks/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at <anonymous>
```

**Comment by imsobear** [comment]
@brizer 试下 iceworks@3.2.5-0  版本 https://github.com/ice-lab/iceworks/pull/88/files

**Comment by brizer** [comment]
这次好了。正常报错了，然后我创建站点并选择后，可以正常了。感谢。
<img src="https://raw.githubusercontent.com/brizer/graph-bed/master/img/20200611131208.png"/>

**Comment by tao1991123** [comment]
> 这次好了。正常报错了，然后我创建站点并选择后，可以正常了。感谢。
> ![](https://raw.githubusercontent.com/brizer/graph-bed/master/img/20200611131208.png)

记得重置一下你的个人token  你的token已经泄露了
