### ISSUE TITLE
单元测试 store无法访问

### ISSUE THREAD

**Issue by Gamehu** [alibaba/ice#3379]
Do you want to request a feature or report a bug?
feature
What is the current behavior?
基于iceworks创建的项目，按照ice的方式创建了services+models+components，现在想要测试components页面如下

组件源码：
 ```
import React, { useEffect } from 'react';
import { Grid, Tab } from '@alifd/next';
import { store as pageStore } from 'ice/ResourceCenter';
import ResourceList from './components/list.jsx';
import styles from './index.module.scss';
import ResourceTypeTree from './components/tree.jsx';
import DetailConfig from './components/detail_config.jsx';

const { Row, Col } = Grid;

const AlarmAnalyze = () => {
  const [treeState, treeDispatchers] = pageStore.useModel('tree');
  const [listState, listDispatchers] = pageStore.useModel('list');
  ...
```

单元测试用例：

```
import React from 'react'
import AlarmAnalyze from '../../src/pages/ResourceCenter/index'
import { shallow } from 'enzyme'

describe('render', () => {
	test('find AlarmAnalyze', () => {
		const wrapper = shallow(<AlarmAnalyze />)
		expect(wrapper.find('.layout-content')).not.toBeNull()
	})
})
```

icejs version： **1.6.4-alpha.0**
Node verson：12.18.2
What is the expected behavior?

"test": "icejs test --jest-coverage",
运行测试：npm run test

得到如下异常，无法访问store里的数据
```

  TypeError: Cannot read property 'store' of null

      10 | 
      11 | const AlarmAnalyze = () => {
    > 12 |   const [treeState, treeDispatchers] = pageStore.useModel('tree');
         |                                                  ^
      13 |   const [listState, listDispatchers] = pageStore.useModel('list');

      at Object.useSelector (node_modules/react-redux/lib/hooks/useSelector.js:115:34)
      at useModelState (node_modules/@ice/store/src/plugins/modelApis.tsx:26:32)
      at Object.useModel (node_modules/@ice/store/src/plugins/modelApis.tsx:21:23)
      at AlarmAnalyze (src/pages/ResourceCenter/index.jsx:12:50)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:645:55)
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
      at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:645:20)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:411:22)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (test/pages/index.test.js:7:19)

```

请问怎么才能使单元/集成测试能像正常打开页面一样访问**ice的store**

**Comment by LanceZhu** [comment]
对于使用到 `store` 的组件，在测试时需要包裹一层 `store provider`。可参考 [basic-store](https://github.com/alibaba/ice/blob/release-next/examples/basic-store/src/pages/Home/__tests__/index.tsx) 中的写法。

**Comment by Gamehu** [comment]
> 对于使用到 `store` 的组件，在测试时需要包裹一层 `store provider`。可参考 [basic-store](https://github.com/alibaba/ice/blob/release-next/examples/basic-store/src/pages/Home/__tests__/index.tsx) 中的写法。

OK，Thanks
