### ISSUE TITLE
icejs升级到1.7.0以后无法运行项目

### ISSUE THREAD

**Issue by pengwangpengwang** [alibaba/ice#3450]
WARN: module.ts(x) will not be supported in the future. Please rename as runtime.ts(x) in /Users/wangpeng/code/car-assets/node_modules/_build-plugin-ice-router@1.1.5@build-plugin-ice-router/lib/module.js
WARN: module.ts(x) will not be supported in the future. Please rename as runtime.ts(x) in /Users/wangpeng/code/car-assets/node_modules/_build-plugin-ice-logger@1.1.5@build-plugin-ice-logger/lib/module.js
WARN: module.ts(x) will not be supported in the future. Please rename as runtime.ts(x) in /Users/wangpeng/code/car-assets/node_modules/_build-plugin-ice-request@1.1.5@build-plugin-ice-request/lib/module.js
WARN: module.ts(x) will not be supported in the future. Please rename as runtime.ts(x) in /Users/wangpeng/code/car-assets/node_modules/_build-plugin-ice-store@1.1.5@build-plugin-ice-store/lib/module.js
ERR! CONFIG Failed to get config.
ERR! targets already registered in userConfig 
Error: targets already registered in userConfig
    at configArr.forEach (/Users/wangpeng/code/car-assets/node_modules/_@alib_build-scripts@0.1.27@@alib/build-scripts/lib/core/Context.js:44:27)
    at Array.forEach (<anonymous>)
    at Context.registerConfig (/Users/wangpeng/code/car-assets/node_modules/_@alib_build-scripts@0.1.27@@alib/build-scripts/lib/core/Context.js:41:23)
    at Context.registerUserConfig (/Users/wangpeng/code/car-assets/node_modules/_@alib_build-scripts@0.1.27@@alib/build-scripts/lib/core/Context.js:242:18)
    at module.exports (/Users/wangpeng/code/car-assets/node_modules/_build-plugin-react-app@1.1.5@build-plugin-react-app/src/index.js:103:3)
    at Context.runPlugins (/Users/wangpeng/code/car-assets/node_modules/_@alib_build-scripts@0.1.27@@alib/build-scripts/lib/core/Context.js:271:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by chenbin92** [comment]
看起来是依赖的版本没有更新到。贴一下 package.json 的依赖信息
