### ISSUE TITLE
webpack插件按照文档配置，build时报错

### ISSUE THREAD

**Issue by leiyily** [alibaba/ice#4032]
"webpackPlugins": {
        "webpack.ProvidePlugin": {
            "options": {
                "_": "lodash"
            }
        },
        "copy-webpack-plugin": {
            "patterns": [
                { "from": "../subapps", "to": "./build" }
            ]
        },
        "HtmlWebpackPlugin": {
            "after": "copy-webpack-plugin"
        }
    }

webpack.ProvidePlugin这么写报错

info 自定义 Fusion 组件主题变量： { nextPrefix: 'next-icestark-' }
ERR! Invalid plugin configuration: plugin('webpack./ProvidePlugin').use(<Plugin>) was not called to specify the plugin 
Error: Invalid plugin configuration: plugin('webpack./ProvidePlugin').use(<Plugin>) was not called to specify the plugin
    at Object.toConfig (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Plugin.js:60:15)
    at clean.Object.assign.plugins.plugins.values.map (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Config.js:129:63)
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Config.js:129:40)
    at configArr.map.v (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_@alib_build-scripts@0.1.30@@alib/build-scripts/lib/commands/build.js:53:60)
    at Array.map (<anonymous>)
    at module.exports (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_@alib_build-scripts@0.1.30@@alib/build-scripts/lib/commands/build.js:53:37)

copy-webpack-plugin这个插件配置不生效

**Comment by luhc228** [comment]
icejs@1.15.0 发布已解决该问题
