### ISSUE TITLE
从 ice-scripts 2.x 迁移icejs后 npm start 报错compilation.getAssets is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by rory-wang** [alibaba/ice#4076]
从 ice-scripts 2.x 迁移icejs后 npm start 报错compilation.getAssets is not a function or its return value is not iterable

```
D:\Work space\posidon\node_modules\build-scripts-config\node_modules\mini-css-extract-plugin\dist\loader.js:122
    for (const asset of compilation.getAssets()) {
                                    ^

TypeError: compilation.getAssets is not a function or its return value is not iterable
    at D:\Work space\posidon\node_modules\build-scripts-config\node_modules\mini-css-extract-plugin\dist\loader.js:122:37
    at D:\Work space\posidon\node_modules\webpack\lib\Compiler.js:300:11
    at D:\Work space\posidon\node_modules\webpack\lib\Compiler.js:556:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Work space\posidon\node_modules\webpack\lib\Compiler.js:553:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Work space\posidon\node_modules\webpack\lib\Compilation.js:1323:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Work space\posidon\node_modules\webpack\lib\Compilation.js:1314:32
    at eval (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at processEntryChunk (D:\Work space\posidon\node_modules\build-plugin-fusion\lib\webpackPlugins\appendStyleWebpackPlugin.js:104:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:5:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Work space\posidon\node_modules\webpack\lib\Compilation.js:1309:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Work space\posidon\node_modules\webpack\lib\Compilation.js:1305:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Work space\posidon\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Work space\posidon\node_modules\tapable\lib\Hook.js:154:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/cms-scaffold@3.0.5 start: `icejs start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @icedesign/cms-scaffold@3.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by imsobear** [comment]
提供下原先的 ice.config.js 以及新的 build.json 的内容

**Comment by rory-wang** [comment]
build.json  

{
    "plugins": [
      [
        "build-plugin-fusion",
        {
          "themePackage": "@icedesign/theme"
        }
      ],
      [
        "build-plugin-moment-locales",
        {
          "locales": [
            "zh-cn"
          ]
        }
      ]
    ]
  }

ice.config.js

```javascript
const path = require('path');

module.exports = {
  entry: 'src/index.jsx',
  hash: true,
  publicPath: './',
  plugins: [
    ['ice-plugin-fusion', {
      themePackage: '@icedesign/theme',
    }],
    ['ice-plugin-moment-locales', {
      locales: ['zh-cn'],
    }],
  ],
  alias: {
    '@': path.resolve(__dirname, './src/'),
  },
};
```

多谢

**Comment by ClarkXia** [comment]
看错误信息是 mini-css-extract-plugin 的报错，确认下是否在升级完成后删除所有依赖，重新安装过一遍

**Comment by rory-wang** [comment]
我用iceworks 点击了重装依赖，还是一样报错信息。

**Comment by ClarkXia** [comment]
> 我用iceworks 点击了重装依赖，还是一样报错信息。

提供下简单的 demo

**Comment by rory-wang** [comment]
非常感谢支持，
我删除本地node_moduls文件夹和package-lock.json文件，重新install后，问题解决了，

应该是iceworks里面的重新安装依赖，并没有真的重新安装。

**Comment by rory-wang** [comment]
建议在官方迁移文档 https://ice.work/docs/guide/migrate
里面补充一下，配置修改完成后重新安装依赖，这一步骤。

希望飞冰（ice.work）越做越好。
