### ISSUE TITLE
ICE升级到1.17.2后启动报错

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#4197]
原先1.16.0没问题，今天升级到1.17.2后不知道为什么报错了，是不是少升级了什么依赖，从官网上拉下来的项目又没什么问题，也是奇怪了：

```
ERR! CONFIG Failed to get config.
ERR! getLessImplementation is not a function
TypeError: getLessImplementation is not a function
    at module.exports (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@builder\user-config\lib\userConfig\lessLoaderOptions.js:10:21)
    at configWebpack (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@builder\user-config\lib\applyUserConfig.js:35:11)
    at Context.<anonymous> (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:446:23)
    at Generator.next (<anonymous>)
    at C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:4:12)
    at Context.runConfigWebpack (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:442:16)
    at Context.<anonymous> (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:355:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ChenFeng\VSCode\pfws.ice.erp\node_modules\@alib\build-scripts\lib\core\Context.js:5:58)
```

**Comment by ClarkXia** [comment]
重装依赖的时候先删除原 node_modules 依赖，再重新安装，推荐使用 `npm update` 命令
