### ISSUE TITLE
创建模版失败  

### ISSUE THREAD

**Issue by zghnzch** [alibaba/ice#428]
{"error":"not_found","reason":"document not found"}Error: {"error":"not_found","reason":"document not found"}
    at Request.s [as _callback] (C:\Users\zchcpy\AppData\Local\Programs\iceworks-desktop\resources\app\main\scaffolder\lib\utils.js:1:2996)
    at Request.self.callback (C:\Users\zchcpy\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\Users\zchcpy\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\Users\zchcpy\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

是因为我更了到了 1.6？

**Comment by zghnzch** [comment]
搞错了  单个模版失败，应该是之前就不行 其它模版可用
