### ISSUE TITLE
从 ice-scripts 1.x 迁移到icejs出现了build错误

### ISSUE THREAD

**Issue by syslink** [alibaba/ice#4357]
我在build.json中的plugins增加了这个配置：
`[
            "build-plugin-fusion", 
            {
                "themePackage": "@alifd/theme-design-pro"
            }
        ],
`
build的时候出现了错误：
`
ERR! (undefined) ./src/pages/Dashboard/components/DisplayCard/DisplayCard.jsx
ERR! Module not found: Can't resolve '@alifd/next/es/feedback' in '/Users/sam/go/src/github.com/bsc/tangping/src/pages/Dashboard/components/DisplayCard'
ERR! 
ERR! (undefined) ./src/pages/Dashboard/components/DisplayCard/DisplayCard.jsx
ERR! Module not found: Can't resolve '@alifd/next/es/feedback/style' in '/Users/sam/go/src/github.com/bsc/tangping/src/pages/Dashboard/components/DisplayCard'
ERR! webpack compile error 
Error: webpack compile error
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_@alib_build-scripts@0.1.31@@alib/build-scripts/lib/commands/build.js:91:28
    at finalCallback (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/MultiCompiler.js:254:12)
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/MultiCompiler.js:277:6
    at done (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_neo-async@2.6.2@neo-async/async.js:2931:13)
    at runCompilers (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/MultiCompiler.js:181:48)
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/MultiCompiler.js:188:7
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:257:39)
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:271:21)
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sam/go/src/github.com/bsc/tangping/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)
    at /Users/sam/go/src/github.com/bsc/tangping/node_modules/_webpack@4.46.0@webpack/lib/Compiler.js:678:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/pro-scaffold@1.0.0 build: `icejs build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @icedesign/pro-scaffold@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2021-06-02T02_50_17_844Z-debug.log
`

在package.json中已经包含了这个包（有安装了）： "@alifd/theme-design-pro": "^0.x"；

请问该如何解决，谢谢

**Comment by ClarkXia** [comment]
`@alifd/next/es/feedback`  在新版的 next 组件中应该没有了  可以看下是不是版本变化过了

**Comment by syslink** [comment]
@ClarkXia 的确是这个原因，现在能build过了，但原来能访问的图片资源，现在显示不出来了，代码如下
`
const logo = require('./images/logo.png');
...
<img style={{width: '48px', height: '48px', marginRight: '21px'}}  src={logo}/>
...
`
后面应该怎么改？谢谢

**Comment by syslink** [comment]
问题都已经解决，谢谢！
