### ISSUE TITLE
[QUESTION]pnpm无法正确执行npm run build

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4719]
```
ice.js 2.0.1
info WEBPACK web:
info WEBPACK   assets by status 1.9 MiB [1m[32m[cached][39m[22m 5 assets
info WEBPACK   [1mweb[39m[22m (webpack 5.47.0) compiled with [1m[31m15 errors[39m[22m and [1m[33m1 warning[39m[22m in 42719 ms
ERR! Module not found: Error: Can't resolve 'react-router' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/core'
ERR! 
ERR! Module not found: Error: Can't resolve 'create-app-shared' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/core'
ERR! 
ERR! Module not found: Error: Can't resolve 'create-app-shared' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/core'
ERR! 
ERR! Module not found: Error: Can't resolve 'react-app-renderer' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/core'
ERR! 
ERR! Module not found: Error: Can't resolve 'process/browser' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/core'
ERR! 
ERR! Module not found: Error: Can't resolve '@ice/runtime' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/request'
ERR! 
ERR! Module not found: Error: Can't resolve 'history' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/router'
ERR! Did you mean './history'?
ERR! Requests that should resolve in the current directory need to start with './'.
ERR! Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/node_modules).
ERR! If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
ERR! 
ERR! Module not found: Error: Can't resolve 'process/browser' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/router/pluginRuntime'
ERR! 
ERR! Module not found: Error: Can't resolve '@loadable/component' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/router/pluginRuntime/runtime'
ERR! 
ERR! Module not found: Error: Can't resolve 'process/browser' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/router/pluginRuntime/runtime'
ERR! 
ERR! Module not found: Error: Can't resolve 'query-string' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/.ice/plugins/router/pluginRuntime/runtime'
ERR! 
ERR! Module not found: Error: Can't resolve 'regenerator-runtime/runtime' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/src'
ERR! 
ERR! Module not found: Error: Can't resolve 'axios' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/src/subtree/shared/src/libs'
ERR! 
ERR! Module not found: Error: Can't resolve 'axios' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/src/subtree/shared/src/libs'
ERR! 
ERR! Module not found: Error: Can't resolve 'querystring' in '/var/lib/jenkins/workspace/cps-mp-admin-web/web/admin/src/subtree/shared/src/libs'
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR! 
ERR! If you want to include a polyfill, you need to:
ERR! 	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
ERR! 	- install 'querystring-es3'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR! 	resolve.fallback: { "querystring": false }
ERR! webpack compile error 
Error: webpack compile error
    at /var/lib/jenkins/workspace/web/admin/node_modules/.pnpm/build-scripts@1.1.1/node_modules/build-scripts/lib/service/build.js:77:28
    at /var/lib/jenkins/workspaceweb/admin/node_modules/.pnpm/@builder+pack@0.3.0/node_modules/@builder/pack/deps/webpack/bundle5.js:71543:14
    at processQueueWorker (/var/lib/jenkins/workspaceweb/admin/node_modules/.pnpm/@builder+pack@0.3.0/node_modules/@builder/pack/deps/webpack/bundle5.js:71480:6)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alifd/scaffold-lite@0.1.0 build: `node src/subtree/shared/scripts/changeFusionSideEffect.js && icejs build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alifd/scaffold-lite@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2021-10-03T07_15_25_719Z-debug.log
```

**Comment by xmsz** [comment]
临时解决办法`--shamefully-hoist`
