### ISSUE TITLE
使用@iceworks/spec，eslint升级到8.0之后，npm run eslint会报错

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#4741]
```
> eslint --cache --ext .ts,.tsx ./


Oops! Something went wrong! :(

ESLint: 8.0.0

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\eslint-config-ali\typescript\react.js » C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\eslint-config-ali\rules\typescript.js': Cannot find module '@typescript-eslint/parser'
Require stack:
- C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\eslint-config-ali\rules\typescript.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.resolve (C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:1088:46)
    at ConfigArrayFactory._loadParser (C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3235:39)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3030:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\YangXB\VSCode\pfws.erp.v2\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3026:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
```

帮忙看看是什么问题，是不是什么包没安装对

**Comment by mopsky** [comment]
收到，感谢

**Comment by fyangstudio** [comment]
https://github.com/alibaba/f2e-spec/pull/42

**Comment by imsobear** [comment]
@iceworks/spec@1.5.0 已兼容 eslint 8
