### ISSUE TITLE
[QUESTION]build显示`TypeError: Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4754]
```
❯ npm run build

> @icedesign/stark-child-scaffold@0.1.0 build /Users/
> icejs build

ice.js 2.0.1
If you see this message, some error occurred in eslint checker. please check your eslint config, see: https://www.yuque.com/hedgqh/quality/lint



info WEBPACK web:
info WEBPACK   assets by status 2.68 MiB [cached] 5 assets
info WEBPACK   web (webpack 5.47.0) compiled with 1 error in 18885 ms
ERR! css/index.css from Css Minimizer
ERR! TypeError: Cannot read property '0' of undefined
ERR!     at Array.forEach (<anonymous>)
ERR!     at runMicrotasks (<anonymous>)
ERR! webpack compile error
Error: webpack compile error
    at /Users/node_modules/build-scripts/lib/service/build.js:77:28
    at /Users/node_modules/@builder/pack/deps/webpack/bundle5.js:71543:14
    at processQueueWorker (/Users/node_modules/@builder/pack/deps/webpack/bundle5.js:71480:6)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/stark-child-scaffold@0.1.0 build: `icejs build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @icedesign/stark-child-scaffold@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2021-10-16T04_32_28_270Z-debug.log

```

npm run start 则一切正常

**Comment by ClarkXia** [comment]
relate to: https://github.com/cssnano/cssnano/issues/1217
