### ISSUE TITLE
sourceMap 设置为true 编译报错

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#4779]
## sourceMap 设置为true 编译报错
```
ERR! Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? } 
ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
    at validate (/Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/terser-webpack-plugin/cjs.js:1:253199)
    at new TerserPlugin (/Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/terser-webpack-plugin/cjs.js:1:254880)
    at /Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:20276
    at Object.toConfig (/Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:21185)
    at /Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:18569
    at Array.map (<anonymous>)
    at e.exports.toConfig (/Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:18560)
    at e.exports.toConfig (/Users/admin/Documents/work/edc-albidata/node_modules/@builder/pack/deps/webpack-chain/Config.js:1:15216)
    at /Users/admin/Documents/work/edc-albidata/node_modules/build-scripts/lib/service/build.js:46:64
    at Array.map (<anonymous>) {
```

分析了一下：新版本的TerserPlugin v5.2.4 应该不支持 sourceMap这个属性配置，但是你们却用到了。icejs对应的源码：
```
module.exports = (config, sourceMap, context) => {
  const { command } = context;
  if (sourceMap && command === 'build') {
    config.devtool(typeof sourceMap === 'string' ? sourceMap : 'source-map');
    config.optimization
      .minimizer('TerserPlugin')
      .tap(([options]) => [
        { ...options, sourceMap: true },
      ]);
  } else if (sourceMap === false) {
    // When sourceMap set false, sourceMap should be closed in dev and build mode
    config.devtool(false);
  }
};
```
## 期望的结果是什么
编译能生产sourceMap
## Any additional comments? 相关环境信息？

- **ice.js Version**： ice.js@2.0.1
- **build.json Configuration**：
```

/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path')
const packConfig = require('./package.json')
const moment = require('moment')
const webpack = require('webpack')

let Version = process.env.Version || 'last'

Version = `${Version.replace(/[./]/g, '_')}_${moment().format('YYYYMMDDHHmmss')}`

module.exports = {
  disableRuntime: true,
  tsChecker: false,
  entry: {
    index: 'src/index.tsx',
    // login: 'src/loginApp/index.tsx',
  },
  sourceMap: true,
  alias: {
    variables: path.resolve(__dirname, './src/styles/variables.less'), // support import in less; example in less file: @import "~variable";
    /**
     * ref: https://github.com/gaearon/react-hot-loader#hot-loaderreact-dom
     * @hot-loader/react-dom replaces the "react-dom" package of the same version, but with additional patches to support hot reloading.
     */
    // 'react-dom': '@hot-loader/react-dom',
    '@': path.resolve(__dirname, './src'),
    types: path.resolve(__dirname, './src/common/types'),
  },
  plugins: [
    ['build-plugin-antd'],
    // ['build-plugin-fast-refresh'],
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
    [
      './build.plugin.js',
      {
        Version,
      },
    ],
  ],
  babelPlugins: [
    [
      'const-enum',
      {
        transform: 'constObject',
      },
    ],
  ],
  extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.html'],
  outputDir: `build/${Version}/`,
  publicPath: `/${Version}/`,
  devServer: {
    historyApiFallback: {
      disableDotRule: true,
      // rewrites: [{ from: /^\/login/, to: '/login.html' }],
    },
  },
  proxy: {
    '/api': {
      enable: true,
      target: packConfig.proxy,
    },
  },
}

```
- **Node Version**: 14.16.1
- **Platform**:  web

**Comment by ClarkXia** [comment]
ice.js 2.1.2 已修复
