### ISSUE TITLE
react error "useLayoutEffect does nothing on the server " in ssr mode

### ISSUE THREAD

**Issue by StarHosea** [alibaba/ice#4826]
## What is the current behavior? 发生了什么？

使用 TypeScript + Ant Design模板，启用 ssr 得到警告：
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect s
hould only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Overflow (G:\+Githome\Icejs\test-ice-ant\build\server\index.js:102496:32)
    at InheritableContextProvider (G:\+Githome\Icejs\test-ice-ant\build\server\index.js:99759:23)
    at Menu (G:\+Githome\Icejs\test-ice-ant\build\server\index.js:98427:32)
    at InternalMenu (G:\+Githome\Icejs\test-ice-ant\build\server\index.js:33206:90)
    at Menu (G:\+Githome\Icejs\test-ice-ant\build\server\index.js:33301:90)
```

## What is the expected behavior? 期望的结果是什么？

正常运行没有警告。

## Any additional comments? 相关环境信息？

- **ice.js Version**： 2.1.1
- **build.json Configuration**：
```
{
  "ssr": true,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}

```
- **Node Version**: v16.12.0
- **Platform**: Windows 10

**Comment by luhc228** [comment]
看上面的警告信息就能得到答案了：https://reactjs.org/link/uselayouteffect-ssr

**Comment by imsobear** [comment]
猜测是 @ant-design/pro-layout 引起的

**Comment by luhc228** [comment]
关联的 issue: https://github.com/ant-design/ant-design/issues/30396

**Comment by imsobear** [comment]
那直接关注 ant-design 的 issue 吧，这里的关掉了 @StarHosea
