### ISSUE TITLE
Mac 启动物料问题

### ISSUE THREAD

**Issue by tuotuogenjudi** [alibaba/ice#483]
报错： siludeMacBook-Air:iceVue siludaluan$ ice-devtools start
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-plugin-component'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at getBabelrc (/usr/local/lib/node_modules/ice-devtools/lib/config/getBabelConfig.js:10:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ice-devtools/lib/config/getWebpackConfig.js:34:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by chenbin92** [comment]
@tuotuogenjudi 使用的 `ice-devtools` 版本多少?  可以升级到最新的版本

**Comment by tuotuogenjudi** [comment]
版本： 1.0.0-beta.18

**Comment by tuotuogenjudi** [comment]
ice-devtools 版本： 1.0.0-beta.18 @chenbin92

**Comment by tuotuogenjudi** [comment]
安装了最新版本 1.0.0-beta.28， 没有问题了 @chenbin92
