### ISSUE TITLE
win7sp1 +ice V2.02 无法创建项目

### ISSUE THREAD

**Issue by xxbld** [alibaba/ice#484]
Can not found version 1.0.0 of @icedesign/analysis-scaffoldError: Can not found version 1.0.0 of @icedesign/analysis-scaffold
    at Request.e [as _callback] (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\main\utils\npmRequest.js:1:562)
    at Request.self.callback (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by noyobo** [comment]
选择的是哪个模板？

**Comment by xxbld** [comment]
ICE Design Analysis，

**Comment by xxbld** [comment]
用npm可以创建，但是install不上啊；cnpm就会报这个错误，

**Comment by noyobo** [comment]
你自己在终端里 install吗？ 如果是要求 node 8 版本

**Comment by xxbld** [comment]
-_-多试几次发现这个错误有点随机，并没有用自己的node环境

**Comment by noyobo** [comment]
稍等 我给你打个包 试下

**Comment by noyobo** [comment]
https://iceworks.oss-cn-hangzhou.aliyuncs.com/win/Iceworks-setup-2.0.4.exe  @xxbld  这个包你试下
