### ISSUE TITLE
Mac/npm 6.0.1/node 6.9.5/ npm start error

### ISSUE THREAD

**Issue by dingjingpisces2015** [alibaba/ice#485]
module.exports = async function (args, subprocess) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at validationSassAvailable.then.then (/Users/dingjing/iceworks-workspace/BlockChain/node_modules/ice-scripts/bin/ice-dev.js:25:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ice-scripts exited unexpectedly.

**Comment by noyobo** [comment]
Please upgrade Node version to v8.11.1 LTS
