### ISSUE TITLE
使用文件约定式路由，开启 ssr 报错

### ISSUE THREAD

**Issue by xiaohp** [alibaba/ice#4861]
## What is the current behavior? 发生了什么？

1. 初始化项目（选择的不带组件库的模板）
2. 删除 routes 配置文件，使用文件约定式路由
3. 开启 ssr 配置，服务报错终止

```
info [SSR] start server render
[HMR] Waiting for update signal from WDS...
/Users/xiaohai/arena/ice-demo/build/server/index.js:4532
Object(function webpackMissingModule() { var e = new Error("Cannot find module './routes'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
                                                 ^

Error: Cannot find module './routes'
    at webpackMissingModule (/Users/xiaohai/arena/ice-demo/build/server/index.js:4532:50)
    at Object../.ice/plugins/ssr/server.ts (/Users/xiaohai/arena/ice-demo/build/server/index.js:4532:133)
    at Module.options.factory (/Users/xiaohai/arena/ice-demo/build/server/index.js:97793:31)
    at __webpack_require__ (/Users/xiaohai/arena/ice-demo/build/server/index.js:97332:33)
    at /Users/xiaohai/arena/ice-demo/build/server/index.js:98307:37
    at Object.<anonymous> (/Users/xiaohai/arena/ice-demo/build/server/index.js:98310:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/xiaohai/arena/ice-demo/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/xiaohai/arena/ice-demo/node_modules/pirates/lib/index.js:104:7) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## What is the expected behavior? 期望的结果是什么？
在 约定路由下使用 ssr

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.0
- **build.json Configuration**：
```json
{
  "vite": false,
  "plugins": [],
  "ssr": true
}

```
- **Node Version**:v16.13.0
- **Platform**:macOS

**Comment by luhc228** [comment]
感谢反馈！确实有这个问题，我们修复一下

**Comment by ClarkXia** [comment]
2.2.0 版本已修复
