### ISSUE TITLE
npm run build 构建失败 Mac环境

### ISSUE THREAD

**Issue by WaveStill** [alibaba/ice#491]
求大佬帮忙解释下：
打包构建的时候，构建失败，报错为：
@icedesign/scaffold-create-react-app@1.0.0 build /Users/apple/react/ice-formwork/ice-demo
> react-app-rewired build

/Users/apple/react/ice-formwork/ice-demo/rewire-scss.js:27
  styleLoaderRule.use.push({
                      ^

TypeError: Cannot read property 'push' of undefined
    at rewireSass (/Users/apple/react/ice-formwork/ice-demo/rewire-scss.js:27:23)
    at Object.override [as webpack] (/Users/apple/react/ice-formwork/ice-demo/config-overrides.js:24:12)
    at Object.<anonymous> (/Users/apple/react/ice-formwork/ice-demo/node_modules/react-app-rewired/scripts/build.js:11:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by chenbin92** [comment]
贴一下 `rewire-scss.js` 文件的代码

**Comment by WaveStill** [comment]
OK了，谢谢大佬帮忙解决...
