### ISSUE TITLE
模板启动报错

### ISSUE THREAD

**Issue by God-gill** [alibaba/ice#4929]
模板启动会正常但是修改js文件并保存后就会报错
我用ice.js 2.x 版本 antd模板建立的项目会报错， 以下是node环境 16.13.0
node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
Error: Failed to load plugin 'react' declared in '.eslintrc.js » D:\FcCode\big-platform\node_modules\@iceworks\spec\node_modules\eslint-config-ali\typescript\react.js » D:\FcCode\big-platform\node_modules\@iceworks\spec\node_modules\eslint-config-ali\react.js » D:\FcCode\big-platform\node_modules\@iceworks\spec\node_modules\eslint-config-ali\rules\react.js': Cannot find module 'eslint-plugin-react'
Require stack:
- D:\FcCode\big-platform\__placeholder__.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.resolve (D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\shared\relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\config-array-factory.js:1017:39)
    at D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\config-array-factory.js:908:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\config-array-factory.js:904:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\config-array-factory.js:725:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (D:\FcCode\big-platform\node_modules\@eslint\eslintrc\lib\config-array-factory.js:665:20)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\FcCode\\big-platform\\__placeholder__.js' ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-react',
    resolvePluginsRelativeTo: 'D:\\FcCode\\big-platform',
    importerName: '.eslintrc.js » D:\\FcCode\\big-platform\\node_modules\\@iceworks\\spec\\node_modules\\eslint-config-ali\\typescript\\react.js » D:\\FcCode\\big-platform\\node_modules\\@iceworks\\spec\\node_modules\\eslint-config-ali\\react.js » D:\\FcCode\\big-platform\\node_modules\\@iceworks\\spec\\node_modules\\eslint-config-ali\\rules\\react.js'
  }
}

**Comment by ClarkXia** [comment]
修改保存会执行增量 eslint 检测，可以先通过以下方式关闭，我们在 windows 上复现下这个问题：

```json
{
  "eslint": false
}
```

**Comment by God-gill** [comment]
好的，

**Comment by Tenodec** [comment]
我也遇到类似的问题，想体验下ice，之前是umi。运行 fusion-design-pro模板会报在xxxxx/venn.js 找不到 ../node_module/fmin.最后发现venn这个包三年不更新了，不知是哪个模板用了这个包。使用fusion-design这个模板运行就能成功， fusion-design-pro模板删除掉模板代码和一些依赖，就可以运行，在venn下安装fmin也可以运行

**Comment by ClarkXia** [comment]
@Tenodec 参考这个 issue 说明 https://github.com/alibaba-fusion/materials/issues/134
