### ISSUE TITLE
ice-devtools start 错误

### ISSUE THREAD

**Issue by zhangxin-github** [alibaba/ice#493]
npm install finished.

   Next step:
     * run `ice-devtools start` to explorer demos
     * run `ice-devtools add` to start your own materials development
========================
请帮忙看下，在安装成功后提示上述信息后，运行ice-devtools start报错，详细信息如下：

$ ice-devtools start
/usr/local/lib/node_modules/ice-devtools/lib/server/index.js:52
          app.use(async function(ctx, next) {
                  ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ice-devtools/bin/ice-devtools-start.js:9:1)
    at Module._compile (module.js:571:32)

**Comment by chenbin92** [comment]
麻烦提供一下使用的 `ice-devtools` 的版本以及运行环境相关的信息

**Comment by zhangxin-github** [comment]
ice-devtools 1.0.0-beta-30
node v7.4.0
npm 4.0.5

**Comment by yuanyan** [comment]
@zhangxin-github 升级到node 8 版本，@chenbin92 在包里设置最小的node版本，同时运行检测
