### ISSUE TITLE
[QUESTION]如何支持worker.ts的引用，现在没有先编译成js

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4947]
背景
```
// index.ts
import test2 from './test1.worker?ts&worker&inline';
```
```
// test1.worker.ts
const a: number = 1;
```
报错
```
[vite] Internal server error: test1.work?ts&worker&inline: 'Const declarations' require an initialization value. (1:7)

> 1 | const a: number = 1;
```
说明ts没有先编译成js

-----

然后我尝试加入 &ts，但好像没有匹配到这个loader进行编译

-----

然后我如果直接js就没问题

需求
- 如何正确引入worker.ts

**Comment by ClarkXia** [comment]
没有 ts 这个 query，直接  `import test2 from './test1.worker?worker&inline';`，另外可以提供下是否开启 vite 模式的信息

**Comment by xmsz** [comment]
> 没有 ts 这个 query，直接 `import test2 from './test1.worker?worker&inline';`，另外可以提供下是否开启 vite 模式的信息

嗯 一开始是`worker&inline'`，发现不行
然后用的是新demo去测试

```
{
  "vite": true,
  "plugins": []
}
```
```
➜  demo-20211119 npm run start

> @alifd/scaffold-simple@0.1.0 start
> icejs start --port 9000

ice.js 2.2.1
  > Local:    http://localhost:9000/
  > Network:  http://192.168.31.82:9000/
上午11:15:54 [vite] Internal server error: /Users/chenshijian/code/demo/demo-20211119/src/pages/Home/test1.work.ts?worker&inline: 'Const declarations' require an initialization value. (1:7)

> 1 | const a: number = 1;
    |        ^
  2 |
  Plugin: vite:react-babel
  File: /Users/chenshijian/code/demo/demo-20211119/src/pages/Home/test1.work.ts?worker&inline
  1  |  const a: number = 1;
     |         ^
  2  |  
      at Object._raise (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)
      at Object.raiseWithData (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)
      at Object.raise (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)
      at Object.parseVar (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:14026:18)
      at Object.parseVarStatement (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13836:10)
      at Object.parseStatementContent (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13421:21)
      at Object.parseStatement (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13352:17)
      at Object.parseBlockOrModuleBlockBody (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13941:25)
      at Object.parseBlockBody (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13932:10)
      at Object.parseProgram (/Users/chenshijian/code/demo/demo-20211119/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13272:10)


```

**Comment by ClarkXia** [comment]
vite 模式下应该是用了 vite 默认的资源 query 能力，这个我们出现解决方案

**Comment by ClarkXia** [comment]
确认是 vite 插件引入的问题，目前已确认修复，具体可以参考 https://github.com/vitejs/vite/issues/5752
