### ISSUE TITLE
ice-devtools generate 生成物料 DB报错；

### ISSUE THREAD

**Issue by tuotuogenjudi** [alibaba/ice#499]
npm publish 成功后，执行ice-devtools generate 报错如下：
/usr/local/lib/node_modules/ice-devtools/database/generate.js:7
  for (let i = 0; i < materialList.length; i++) {
                                  ^

TypeError: Cannot read property 'length' of null
    at generate (/usr/local/lib/node_modules/ice-devtools/database/generate.js:7:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/ice-devtools/bin/ice-devtools-generate.js:4:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

npm 版本：6.0.1
node版本： v8.2.1
ice-devtools版本： 1.0.0-beta.28

**Comment by chenbin92** [comment]
@tuotuogenjudi  贴一下根目录下的 `package.json` 的 `materials` 字段描述信息

**Comment by tuotuogenjudi** [comment]
@chenbin92 ,materials字段如下，我是对layouts里的布局进行单独发布的
"materials": [
    {
      "directory": "react-materials",
      "type": "react"
    },
    {
      "directory": "vue-materials",
      "type": "vue"
    }
  ]

**Comment by chenbin92** [comment]
@tuotuogenjudi  需要在项目根目录执行生成 DB 数据
