### ISSUE TITLE
从2.2.3 升级到 2.3.0 报错

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#5001]
## What is the current behavior? 发生了什么？
升级2.3.0 后 编译报错。2.3.0 是否没考虑 禁用 disableRuntime 的情况？
```
ERR! CONFIG Failed to get config.
ERR! The "path" argument must be of type string. Received undefined 
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at /Users/admin/Documents/work/training-h5/node_modules/build-plugin-react-app/lib/index.js:81:78
    at BuildService.<anonymous> (/Users/admin/Documents/work/training-h5/node_modules/build-scripts/lib/core/Context.js:516:27)
    at Generator.next (<anonymous>)
    at /Users/admin/Documents/work/training-h5/node_modules/build-scripts/lib/core/Context.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/Documents/work/training-h5/node_modules/build-scripts/lib/core/Context.js:4:12)
    at BuildService.Context.runWebpackFunctions (/Users/admin/Documents/work/training-h5/node_modules/build-scripts/lib/core/Context.js:495:42)
    at BuildService.<anonymous> (/Users/admin/Documents/work/training-h5/node_modules/build-scripts/lib/core/Context.js:525:24) {
  code: 'ERR_INVALID_ARG_TYPE'
```

## Any additional comments? 相关环境信息？
```
const path = require('path')
const moment = require('moment')

let Version = process.env.Version || 'last'
// const ENV = process.env.ENV || 'Production' // 环境

Version = `${Version.replace(/[./]/g, '_')}_${moment().format('YYYYMMDDHHmmss')}`

// const RELEASE = Version

module.exports = {
  disableRuntime: true,
  eslint: false,
  // entry: 'src/index.tsx',
  entry: {
    index: 'src/index.tsx',
  },
  alias: {
    variables: path.resolve(__dirname, './src/style/variables.less'), // support import in less; example in less file: @import '~variable';
    /**
     * ref: https://github.com/gaearon/react-hot-loader#hot-loaderreact-dom
     * @hot-loader/react-dom replaces the 'react-dom' package of the same version, but with additional patches to support hot reloading.
     */
    // 'react-dom': '@hot-loader/react-dom',
    '@': path.resolve(__dirname, './src'),
    types: path.resolve(__dirname, './src/common/types'),
  },
  customWebpack: true,
  plugins: [
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
    [
      './build.plugin.js',
      {
        Version,
      },
    ],
  ],
  babelPlugins: [
    [
      'const-enum',
      {
        transform: 'constObject',
      },
    ],
  ],
  extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.html'],
  outputDir: `build/${Version}/`,
  publicPath: `/${Version}/`,
  devServer: {
    historyApiFallback: {
      disableDotRule: true,
      // rewrites: [{ from: /^\/login/, to: '/login.html' }],
    },
  },
  postcssOptions: {
    plugins: {
      'postcss-pxtorem': {
        rootValue: 37.5,
        unitPrecision: 3,
        propList: ['*'],
        minPixelValue: 1,
        exclude: /node_modules/i,
      },
    },
  },
  proxy: {
    '/api': {
      target: 'http://testsale-traing-api.cn',
      pathRewrite: { '^/api/h5': '/h5' },
      enable: true,
      changeOrigin: true,
    },
  },
}

```
- **ice.js Version**：2.3.0
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
修复中 可以试下 ice.js@2.3.1-beta.1
