### ISSUE TITLE
icejs 的proxy不支持https吗？

### ISSUE THREAD

**Issue by chandlerzyn** [alibaba/ice#5101]
接口的链接是https的。设置proxy后直接报错了
"proxy": {
    "/home/user": {
      "target": "https://xml.alibaba.net/"
    }
  }
报错信息是
[vite] http proxy error:
Error: unable to get local issuer certificate

**Comment by ClarkXia** [comment]
启动的时候是否开启了 https？

**Comment by chandlerzyn** [comment]
这个要怎么开启？

**Comment by chandlerzyn** [comment]
开启了 这个密码是开机密码吗

**Comment by chandlerzyn** [comment]
配置了。还是这样。看了一下ssl证书有了。但是还是报这个错

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/a9af9598812fa21b1eed1e48df0110d956938484/examples/basic-vite/build.json#L14-L19

通过将 http://jsonplaceholder.typicode.com 修改成 https://jsonplaceholder.typicode.com 无法复现出你的问题，对于 unable to get local issuer certificate 的报错可能是证书的问题，最好能提供一个复现的 case

**Comment by we6288815** [comment]
我这边后端使用的自签名证书，配置https代理的时候也不行，我浏览器已经导入并信任了CA
```
下午3:45:46 [vite] http proxy error:
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
```
