### ISSUE TITLE
ice-devtools init ice-materials-template app 报错

### ISSUE THREAD

**Issue by SmallRuralDog** [alibaba/ice#512]
```
⠸ downloading template
/usr/local/lib/node_modules/ice-devtools/lib/download.js:52
      const isDone = Object.values(taskComplete).every((done) => done === true);
                            ^

TypeError: Object.values is not a function
    at end (/usr/local/lib/node_modules/ice-devtools/lib/download.js:52:29)
    at WriteStream.entry.pipe.on (/usr/local/lib/node_modules/ice-devtools/lib/download.js:86:11)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at fs.js:2037:14
    at /usr/local/lib/node_modules/ice-devtools/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by SmallRuralDog** [comment]
升级node就可以了 ！！！
