### ISSUE TITLE
[Question] 子应用构建后报错 Cannot read properties of null (reading 'mount')

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#5142]
背景：
- 子应用构建后报错：Cannot read properties of null (reading 'mount')
```
vendor.b95cc0ed.js:41 [@ice/stark] microapp should export mount/unmout or register registerAppEnter/registerAppLeave.
(anonymous) @ vendor.b95cc0ed.js:41
overrideMethod @ react_devtools_backend.js:4045
(anonymous) @ vendor.b95cc0ed.js:27
l @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
a @ vendor.b95cc0ed.js:27
Promise.then (async)
l @ vendor.b95cc0ed.js:27
a @ vendor.b95cc0ed.js:27
Promise.then (async)
l @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
bk @ vendor.b95cc0ed.js:27
Pk @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
l @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
bk @ vendor.b95cc0ed.js:27
Ik @ vendor.b95cc0ed.js:27
n.renderChild @ vendor.b95cc0ed.js:27
n.mountApp @ vendor.b95cc0ed.js:27
t.componentDidMount @ vendor.b95cc0ed.js:27
zp @ vendor.b95cc0ed.js:27
rf @ vendor.b95cc0ed.js:27
e.unstable_runWithPriority @ vendor.b95cc0ed.js:18
mu @ vendor.b95cc0ed.js:27
nf @ vendor.b95cc0ed.js:27
Hd @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
e.unstable_runWithPriority @ vendor.b95cc0ed.js:18
mu @ vendor.b95cc0ed.js:27
gu @ vendor.b95cc0ed.js:27
yu @ vendor.b95cc0ed.js:27
jd @ vendor.b95cc0ed.js:27
Zc @ vendor.b95cc0ed.js:27
(anonymous) @ index.c21677ef.js:1
await in (anonymous) (async)
Xx.r.current.r.current @ vendor.b95cc0ed.js:27
(anonymous) @ index.c21677ef.js:1
uf @ vendor.b95cc0ed.js:27
e.unstable_runWithPriority @ vendor.b95cc0ed.js:18
mu @ vendor.b95cc0ed.js:27
af @ vendor.b95cc0ed.js:27
Hd @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
e.unstable_runWithPriority @ vendor.b95cc0ed.js:18
mu @ vendor.b95cc0ed.js:27
gu @ vendor.b95cc0ed.js:27
yu @ vendor.b95cc0ed.js:27
Wd @ vendor.b95cc0ed.js:27
Af @ vendor.b95cc0ed.js:27
Jn.render @ vendor.b95cc0ed.js:27
am @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
l @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
(anonymous) @ vendor.b95cc0ed.js:27
tm @ vendor.b95cc0ed.js:27
im @ vendor.b95cc0ed.js:27
ct @ index.c21677ef.js:1
(anonymous) @ index.c21677ef.js:1
vendor.b95cc0ed.js:27 Uncaught (in promise) Error: [icestark] You are not support to use `loadScriptMode = import` where dynamic import is not supported by browsers.
    at vendor.b95cc0ed.js:27:229858
    at l (vendor.b95cc0ed.js:27:228738)
    at Object.throw (vendor.b95cc0ed.js:27:228042)
    at s (vendor.b95cc0ed.js:27:227632)
```

**Comment by maoxiaoke** [comment]
icestark 是哪个版本的

**Comment by WITfeng** [comment]
我也有这个问题，子应用icestart版本是2.7.1
![image](https://user-images.githubusercontent.com/22720410/149744446-f22d6b2c-6b5c-49c6-9efb-44b9274c1307.png)

**Comment by yiescc** [comment]
> icestark

2.4.2

**Comment by maoxiaoke** [comment]
https://micro-frontends.ice.work/error/?code=1&arg=/seller @yiescc 这个错误跟这个是一致的，看下是否可以有帮助

**Comment by ChenLeoXX** [comment]
有解决吗，基于vue-cli构建的 按照文档配置了 umd，还有umd名称 还是报这个错，查看window.microApp这个属性有值，但是status是not-lodaed

**Comment by maoxiaoke** [comment]
> 有解决吗，基于vue-cli构建的 按照文档配置了 umd，还有umd名称 还是报这个错，查看window.microApp这个属性有值，但是status是not-lodaed

可以贴一下子应用配置

**Comment by ChenLeoXX** [comment]
vue2.0 CLI配置 ![image](https://user-images.githubusercontent.com/27530887/156952991-23c56480-c3d1-4815-81ba-96aa731e1766.png)
![image](https://user-images.githubusercontent.com/27530887/156953027-acdfefd4-b23a-45d9-b97f-8b575b28eda7.png)
main.js 配置

**Comment by ChenLeoXX** [comment]
> 

打包出来后 因为可能有异步懒加载的路由 和组件 会分chunk文件 和入口文件，主应用配置信息使用url 就会报 没导出。

**Comment by maoxiaoke** [comment]
@ChenLeoXX 可以移除懒加载试下
