### ISSUE TITLE
使用 mock 方案 response 对象缺失 send 方法

### ISSUE THREAD

**Issue by sgfily** [alibaba/ice#5154]
下午12:13:08 [vite] Internal server error: res.send is not a function
      at GET /api/menu/getMenus (E:\gitcode\web\mock-project\mock\/index.ts:5:9)
      at E:\gitcode\web\mock-project\node_modules\webpack-dev-mock\lib\index.js:188:21
      at multerMiddleware (E:\gitcode\web\mock-project\node_modules\multer\lib\make-middleware.js:18:41)
      at sendData (E:\gitcode\web\mock-project\node_modules\webpack-dev-mock\lib\index.js:187:31)
      at Object.handler (E:\gitcode\web\mock-project\node_modules\webpack-dev-mock\lib\index.js:181:13)
      at E:\gitcode\web\mock-project\node_modules\webpack-dev-mock\lib\index.js:139:26
      at call (E:\gitcode\web\mock-project\node_modules\.pnpm\connect@3.7.0\node_modules\connect\index.js:239:7)
      at next (E:\gitcode\web\mock-project\node_modules\.pnpm\connect@3.7.0\node_modules\connect\index.js:183:5)
      at Function.handle (E:\gitcode\web\mock-project\node_modules\.pnpm\connect@3.7.0\node_modules\connect\index.js:186:3)
      at Server.app (E:\gitcode\web\mock-project\node_modules\.pnpm\connect@3.7.0\node_modules\connect\index.js:51:37)

**Comment by ClarkXia** [comment]
vite 模式下需要使用 `res.end`

**Comment by imsobear** [comment]
> vite 模式下需要使用 `res.end`

这种要抹平吗？

**Comment by sgfily** [comment]
有办法不用res.end吗 这种很麻烦 还需要手写contentType 还要json.stringfy

**Comment by sgfily** [comment]
> vite模式下需要使用`res.end`

这种很麻烦 还需要手写content-type json.stringfy 有办法 用send吗

**Comment by inier** [comment]
mock下我已经放弃 res.send， 老老实实的写值 {}
