### ISSUE TITLE
开启 swc 后 gitlab-ci 环境下 swc 编译失败

### ISSUE THREAD

**Issue by aak1247** [alibaba/ice#5231]
## What is the current behavior? 发生了什么？
gitlab-ci环境下swc编译失败，报错信息如下：
```bash
$ CI=false npm run build:test


> @icedesign/ice-antd-scaffold@0.1.0 build:test
> icejs build --mode test

ice.js 2.6.0
info [swc] swc enabled, configurations about babel will be ignored
info 自定义 antd 组件主题变量： { 'primary-color': '#205FED' }
[ERROR] optimize runtime failed when analyze /xxxx.jsx
info WEBPACK web:
info WEBPACK   assets by status 914 KiB 
[cached]
 5 assets
info WEBPACK   
web
 (webpack 5.67.0) compiled with 
1 error
 in 20732 ms
ERR! Error: Cannot find target @builder/swc native module!
ERR! webpack compile error 
Error: webpack compile error
    at /builds/Develop/devops/large-platform/node_modules/build-scripts/lib/service/build.js:81:28
    at /builds/Develop/devops/large-platform/node_modules/@builder/pack/deps/webpack/bundle5.js:73772:14
    at processQueueWorker (/builds/Develop/devops/large-platform/node_modules/@builder/pack/deps/webpack/bundle5.js:73709:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
## Any additional comments? 相关环境信息？
gitlab runner -v：
```bash
Version:      14.0.1
Git revision: c1edb478
Git branch:   refs/pipelines/336930390
GO version:   go1.13.8
Built:        2021-07-14T13:28:49+0000
OS/Arch:      linux/amd64
```
构建镜像dockerfile：
```dockerfile
FROM node:16.2.0-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
COPY node-sass-linux-x64-102_binding.node /root/download/nodesass/
RUN apk add --no-cache tzdata git gcc cmake make g++ alpine-sdk python3 \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/* $HOME/.cache
RUN npm config set cache /root/cache/.npm/cache \
    && npm config set unsafe-perm true \
    && npm config set registry xxxx
RUN  npm install -g node-sass --sass-binary-path=/root/download/nodesass/node-sass-linux-x64-102_binding.node \
    && npm install --global yarn --force \
    && npm install --global lerna --force \
    && npm install --global pnpm --force
RUN yarn config set yarn-offline-mirror /root/cache/.yarn/offline-mirror \
    && yarn config set cache-folder /root/cache/.yarn/cache \
    && yarn config set global-folder /root/cache/.yarn/global
RUN pnpm config set store-dir /root/cache/.pnpm/store
COPY docker /usr/local/bin/
```

- **ice.js Version**：2.4.0
- **build.json Configuration**：
```json
{
  "eslint": false,
  "swc": true,
  "modeConfig": {
    //...
  },
  "plugins": [
    [
      "build-plugin-antd",
      {
        "disableModularImport": true,
        "themeConfig": {
          "primary-color": "#205FED"
        }
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ],
    [
      "build-plugin-icestark",
      {
        "type": "child",
        "umd": true
      }
    ]
  ],
  "minify": {
    "type": "swc",
    "options": {
      "compress": {
        "drop_console": true
      }
    }
  }

```
- **Node Version**: 16.2.0
- **Platform**: alpine 3.13.5

**Comment by ClarkXia** [comment]
对应平台的产物未编译

**Comment by aak1247** [comment]
这个问题如何处理？有处理思路的话我们可以自己处理一下然后给个pr

**Comment by imsobear** [comment]
> 这个问题如何处理？有处理思路的话我们可以自己处理一下然后给个pr

我们最近这个版本处理下。

**Comment by SoloJiang** [comment]
目前已经发版也可以关掉 swc 不阻塞构建，这周看下怎么支持 linux arm64
