### ISSUE TITLE
[QUESTION]出现「Rollup failed to resolve import "/src/app" from "index.html".」

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#5347]
repo https://github.com/xmsz/demo-2022060902
```
cnpm i 
npm run build

```
```
demo-2022060902 npm run build

> @alifd/scaffold-simple@0.1.0 build
> icejs build

ice.js 2.6.4
info [analyze] build-plugin-ice-request removed after runtime analyse
[Error] errors occurred with analyze runApp
vite v2.9.10 building for production...
✓ 2 modules transformed.
[vite]: Rollup failed to resolve import "/src/app" from "index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Vite Failed to build.
ERR! [vite]: Rollup failed to resolve import "/src/app" from "index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "/src/app" from "index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/var/lib/jenkins/workspace/demo-2022060902/node_modules/_vite@2.9.10@vite/dist/node/chunks/dep-9e5491c9.js:41772:19)
    at onwarn (/var/lib/jenkins/workspace/demo-2022060902/node_modules/_vite@2.9.10@vite/dist/node/chunks/dep-9e5491c9.js:41588:13)
    at Object.onwarn (/var/lib/jenkins/workspace/demo-2022060902/node_modules/_rollup@2.75.6@rollup/dist/shared/rollup.js:23224:13)
    at ModuleLoader.handleResolveId (/var/lib/jenkins/workspace/demo-2022060902/node_modules/_rollup@2.75.6@rollup/dist/shared/rollup.js:22508:26)
    at /var/lib/jenkins/workspace/demo-2022060902/node_modules/_rollup@2.75.6@rollup/dist/shared/rollup.js:22469:26 {
  watchFiles: [
    '/var/lib/jenkins/workspace/demo-2022060902/index.html',
    'vite/modulepreload-polyfill'
  ]
}
➜  demo-2022060902 git:(46f7fe0)
```

其他信息
- 我在本地运行没有问题
- 我使用新的项目在出问题的环境中允许也没有问题
- 出问题的这个项目 内容我也全部替换成了默认的问题

**Comment by xmsz** [comment]
我尝试修改 build.json
```
"entry": "./src/App.tsx"
```

虽然提示'[Error] errors occurred with analyze runApp'， 但至少编译成功了

```
ice.js 2.6.4
info 开启文件约定式路由能力 
info [analyze] build-plugin-ice-request removed after runtime analyse
[Error] errors occurred with analyze runApp
[36mvite v2.9.10 [32mbuilding for production...[36m[39m
transforming...
[32m✓[39m 129 modules transformed.
rendering chunks...
[90m[37m[2mbuild/[22m[90m[39m[32mindex.html     [39m [2m0.40 KiB[22m
[90m[37m[2mbuild/[22m[90m[39m[35mcss/index.css  [39m [2m0.23 KiB / gzip: 0.18 KiB[22m
[90m[37m[2mbuild/[22m[90m[39m[36mjs/index.js    [39m [2m198.84 KiB / gzip: 65.07 KiB[22m
Finished: SUCCESS
```

**Comment by ClarkXia** [comment]
约定的 entry 入口为 src/app，目前 这个是大写的 App

**Comment by xmsz** [comment]
> 约定的 entry 入口为 src/app，修改成小写即可，目前这个是大写的 App store 的问题可以在 demo 中再补充下

原来如此 我把App.tsx=>app.tsx 就可以了
然后store那个改了entry以后的问题 在原demo就可以复现
我先关闭
