### ISSUE TITLE
构件失败

### ISSUE THREAD

**Issue by QKS97** [alibaba/ice#535]
> @icedesign/lite-scaffold@1.0.0 build D:\wamp64\www\KT\kt
> ice build

ice-scripts 1.4.1
sassInfo node-sass	4.9.0	(Wrapper)	[JavaScript]

libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
TIPS: package.json 存在 entry 配置
Tip: 使用皮肤包 @icedesign/skin
皮肤 override 文件存在, 添加...
Hash: 7f25903ec7f520ac4869
Version: webpack 3.12.0
Time: 9908ms
        Asset       Size  Chunks                    Chunk Names
  js/index.js     2.7 MB       0  [emitted]  [big]  index
css/index.css     289 kB       0  [emitted]  [big]  index
   index.html  648 bytes          [emitted]         

ERROR in ./src/pages/Home/components/PerformanceChart/LineChart.jsx
Module not found: Error: Can't resolve '@antv/data-set' in 'D:\wamp64\www\KT\kt\src\pages\Home\components\PerformanceChart'
 @ ./src/pages/Home/components/PerformanceChart/LineChart.jsx 18:0-41
 @ ./src/pages/Home/components/PerformanceChart/PerformanceChart.jsx
 @ ./src/pages/Home/components/PerformanceChart/index.js
 @ ./src/pages/Home/Home.jsx
 @ ./src/pages/Home/index.js
 @ ./src/routerConfig.js
 @ ./src/router.jsx
 @ ./src/index.js
D:\wamp64\www\KT\kt\node_modules\ice-scripts\lib\build.js:66

        throw new Error('webpack compiled failed.');

        ^

Error: webpack compiled failed.

    at D:\wamp64\www\KT\kt\node_modules\ice-scripts\lib\build.js:66:15

    at emitRecords.err (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:265:13)

    at Compiler.emitRecords (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:371:38)

    at emitAssets.err (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:258:10)

    at applyPluginsAsyncSeries1.err (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:364:12)

    at next (D:\wamp64\www\KT\kt\node_modules\webpack\node_modules\tapable\lib\Tapable.js:218:11)

    at Compiler.compiler.plugin (D:\wamp64\www\KT\kt\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)

    at Compiler.applyPluginsAsyncSeries1 (D:\wamp64\www\KT\kt\node_modules\webpack\node_modules\tapable\lib\Tapable.js:222:13)

    at Compiler.afterEmit (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:361:9)

    at require.forEach.err (D:\wamp64\www\KT\kt\node_modules\webpack\lib\Compiler.js:350:15)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/lite-scaffold@1.0.0 build: `ice build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @icedesign/lite-scaffold@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\覃\AppData\Roaming\npm-cache\_logs\2018-05-22T08_02_42_646Z-debug.log

**Comment by chenbin92** [comment]
```
ERROR in ./src/pages/Home/components/PerformanceChart/LineChart.jsx

Module not found: Error: Can't resolve in xxx
```

代码错误，依赖找不到
