### ISSUE TITLE
求助：开启SSR后，如何使用useState和fetchMore功能？

### ISSUE THREAD

**Issue by owendswang** [alibaba/ice#5415]
## What is the current behavior? 发生了什么？

在我开启了SSR功能后，页面需要展示列表类型的信息，服务器端rander第一页内容，但是当我使用useState等动态获取数据的功能时，服务器端报错，说我定义的useState变量不存在。

代码：
```
const Example = (props) => {
  const { res } = props;

  const { moreList, setMoreList } = useState([]);
  const { current, setCurrent } = useState(1);
  const { total, setTotal } = useState(res?.msg?.total || 0 );

  const screens = useBreakpoint();

  const fetchMore = async () => {
    try {
      let result = await request.post({ params: { current: current + 1 } });
      if(result.code) {
        message.error('异常响应');
      } else {
        setCurrent(current + 1);
        setTotal(res.msg.total);
        setMoreList([ ...moreList, ...result.msg.dataSource ]);
      }
    } catch(e) {
      console.log(e);
      message.error('获取数据异常');
    }
  }

  return (
    <>{
      res.msg.dataSource.map((ele, idx) => <>ele</>)
    }{
      moreList.map((ele, idx) => <>ele</>)
    }<Button click={(e) => { fetchMore(); }}></>
  );
}

Example.getInitialProps = async (ctx) => {
  const res = await request.post('http://127.0.0.1:3000/api/example');
  return { res };
}

export default Example;
```

报错信息：
```
ERR! [SSR] generate html template error message: Cannot read properties of undefined (reading 'length')
ERR! [SSR] generate html template error stack: TypeError: Cannot read properties of undefined (reading 'length')
    at Example (/root/App/server/build/server/index.js:26828:22)
    at processChild (/root/App/server/build/server/index.js:153039:14)
    at resolve (/root/App/server/build/server/index.js:152956:5)
    at ReactDOMServerRenderer.render (/root/App/server/build/server/index.js:153439:22)
    at ReactDOMServerRenderer.read (/root/App/server/build/server/index.js:153376:29)
    at Object.renderToString (/root/App/server/build/server/index.js:153984:27)
    at renderInServer (/root/App/server/build/server/index.js:149637:74)
    at reactAppRendererWithSSR (/root/App/server/build/server/index.js:149657:12)
    at _callee2$ (/root/App/server/build/server/index.js:24786:112)
    at tryCatch (/root/App/server/build/server/index.js:24280:2404)
[SSR ERROR] serverRender error TypeError: Cannot read properties of undefined (reading 'length')
    at Example (/root/App/server/build/server/index.js:26828:22)
    at processChild (/root/App/server/build/server/index.js:153039:14)
    at resolve (/root/App/server/build/server/index.js:152956:5)
    at ReactDOMServerRenderer.render (/root/App/server/build/server/index.js:153439:22)
    at ReactDOMServerRenderer.read (/root/App/server/build/server/index.js:153376:29)
    at Object.renderToString (/root/App/server/build/server/index.js:153984:27)
    at renderInServer (/root/App/server/build/server/index.js:149637:74)
    at reactAppRendererWithSSR (/root/App/server/build/server/index.js:149657:12)
    at _callee2$ (/root/App/server/build/server/index.js:24786:112)
    at tryCatch (/root/App/server/build/server/index.js:24280:2404)
```

返回数据内容：
```
{
    "code": 0,
    "msg": {
        "current": 1,
        "pageSize": 10,
        "dataSource": [
            {
                "id": 20,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 19,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 18,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 17,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 16,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 15,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 14,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 13,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 12,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 11,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            }
        ],
        "total": 20
    }
}
```

## What is the expected behavior? 期望的结果是什么？

不知道我该通过什么方式，把动态获取数据功能添加进去，是不是我使用ssr功能的方式不对？还是SSR不能实现这种功能？

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.config.ts Configuration**：
```
export default {
  "vite": false, /*{
    "build": {
      "commonjsOptions": {
        "ignoreTryCatch": false,
      },
    },
  },*/
  // "minify": false,
  "ssr": true,
  "outputDir": "../server/build",
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ], [
      "build-plugin-css-assets-local",
      {
        "outputPath": "assets",
        "relativeCssPath": "../"
      }
    ], [
      "build-plugin-antd",
      {
        "disableModularImport": true,
        "themeConfig": {
          "primary-color": "@blue-base"
        }
      }
    ], [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ]
  ],
  "proxy": {
    "/api": {
      "enable": true,
      "target": "http://127.0.0.1:3000"
    },
    "/uploads": {
      "enable": true,
      "target": "http://127.0.0.1:3000"
    }
  }
}
```
- **Node Version**: 16.16.0
- **Platform**: Ubuntu 20.04 x64

**Comment by ClarkXia** [comment]
提供下具体的错误信息，另外可以 debug 下 getInitialProps 在服务端获取的数据是什么

**Comment by owendswang** [comment]
> 提供下具体的错误信息，另外可以 debug 下 getInitialProps 在服务端获取的数据是什么

报错信息：
```
ERR! [SSR] generate html template error message: Cannot read properties of undefined (reading 'length')
ERR! [SSR] generate html template error stack: TypeError: Cannot read properties of undefined (reading 'length')
    at Life (/root/tmtCiticAppODSW/server/build/server/index.js:26828:22)
    at processChild (/root/tmtCiticAppODSW/server/build/server/index.js:153039:14)
    at resolve (/root/tmtCiticAppODSW/server/build/server/index.js:152956:5)
    at ReactDOMServerRenderer.render (/root/tmtCiticAppODSW/server/build/server/index.js:153439:22)
    at ReactDOMServerRenderer.read (/root/tmtCiticAppODSW/server/build/server/index.js:153376:29)
    at Object.renderToString (/root/tmtCiticAppODSW/server/build/server/index.js:153984:27)
    at renderInServer (/root/tmtCiticAppODSW/server/build/server/index.js:149637:74)
    at reactAppRendererWithSSR (/root/tmtCiticAppODSW/server/build/server/index.js:149657:12)
    at _callee2$ (/root/tmtCiticAppODSW/server/build/server/index.js:24786:112)
    at tryCatch (/root/tmtCiticAppODSW/server/build/server/index.js:24280:2404)
[SSR ERROR] serverRender error TypeError: Cannot read properties of undefined (reading 'length')
    at Life (/root/tmtCiticAppODSW/server/build/server/index.js:26828:22)
    at processChild (/root/tmtCiticAppODSW/server/build/server/index.js:153039:14)
    at resolve (/root/tmtCiticAppODSW/server/build/server/index.js:152956:5)
    at ReactDOMServerRenderer.render (/root/tmtCiticAppODSW/server/build/server/index.js:153439:22)
    at ReactDOMServerRenderer.read (/root/tmtCiticAppODSW/server/build/server/index.js:153376:29)
    at Object.renderToString (/root/tmtCiticAppODSW/server/build/server/index.js:153984:27)
    at renderInServer (/root/tmtCiticAppODSW/server/build/server/index.js:149637:74)
    at reactAppRendererWithSSR (/root/tmtCiticAppODSW/server/build/server/index.js:149657:12)
    at _callee2$ (/root/tmtCiticAppODSW/server/build/server/index.js:24786:112)
    at tryCatch (/root/tmtCiticAppODSW/server/build/server/index.js:24280:2404)
```

返回数据内容：
```
{
    "code": 0,
    "msg": {
        "current": 1,
        "pageSize": 10,
        "dataSource": [
            {
                "id": 20,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 19,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 18,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 17,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 16,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 15,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 14,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 13,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 12,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            },
            {
                "id": 11,
                "title": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "content": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
                "createdAt": "2022-07-22T01:10:14.000Z",
                "updatedAt": null
            }
        ],
        "total": 20
    }
}
```

**Comment by owendswang** [comment]
> 提供下具体的错误信息，另外可以 debug 下 getInitialProps 在服务端获取的数据是什么

求大佬指点迷津！我实在是搜不到相关解释……"在服务器端渲染中添加客户端渲染的功能"。

**Comment by ClarkXia** [comment]
看代码是没什么问题，核心是服务端执行 `request.post('http://127.0.0.1:3000/api/example')` 是否可以走通

**Comment by owendswang** [comment]
> 看代码是没什么问题，核心是服务端执行 `request.post('http://127.0.0.1:3000/api/example')` 是否可以走通

嗯，这个是可以走通的。

看来就是所有react的代码，都将在服务端运行。所以我把点击加载更多改成了原生js语句和dom，就可以跑起来了。
我也只能这样了，多谢。
