### ISSUE TITLE
npm init ice  @icedesign/stark-layout-scaffold 启动项目报错

### ISSUE THREAD

**Issue by versole** [alibaba/ice#5423]
脚手架创建一个项目， npm run start 报错

Expected whitespace.
   ╷
24 │                 @media (min-width: 320px)and(max-width: 479px){ @content; }
   │                                             ^
   ╵
  node_modules/@alifd/next/lib/grid/scss/mixin.scss 24:45  breakpoint()
  node_modules/@alifd/next/lib/grid/scss/mixin.scss 147:9  visible-hidden-all-points()
  node_modules/@alifd/next/lib/grid/main.scss 110:1        @import
  node_modules/@alifd/next/components.scss 27:9            @import
  node_modules/@alifd/next/index.scss 2:9                  @import
  src/global.scss 2480:9                                   root stylesheet
18:42:13 [vite] Internal server error: Expected whitespace.
   ╷
24 │                 @media (min-width: 320px)and(max-width: 479px){ @content; }
   │                                             ^
   ╵
  node_modules/@alifd/next/lib/grid/scss/mixin.scss 24:45  breakpoint()
  node_modules/@alifd/next/lib/grid/scss/mixin.scss 147:9  visible-hidden-all-points()
  node_modules/@alifd/next/lib/grid/main.scss 110:1        @import
  node_modules/@alifd/next/components.scss 27:9            @import
  node_modules/@alifd/next/index.scss 2:9                  @import
  src/global.scss 2480:9                                   root stylesheet
  Plugin: vite:css
  File: /Users/xujingzhu/workspace/race-micro-app/node_modules/@alifd/next/lib/grid/scss/mixin.scss
  Error: Expected whitespace.
     ╷
  24 │                 @media (min-width: 320px)and(max-width: 479px){ @content; }
     │                                             ^
     ╵
    node_modules/@alifd/next/lib/grid/scss/mixin.scss 24:45  breakpoint()
    node_modules/@alifd/next/lib/grid/scss/mixin.scss 147:9  visible-hidden-all-points()
    node_modules/@alifd/next/lib/grid/main.scss 110:1        @import
    node_modules/@alifd/next/components.scss 27:9            @import
    node_modules/@alifd/next/index.scss 2:9                  @import
    src/global.scss 2480:9                                   root stylesheet
      at Object.wrapException (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:1246:17)
      at Object.throwWithTrace0 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:23073:15)
      at MediaQueryParser0.wrapSpanFormatException$1$1 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:90218:13)
      at MediaQueryParser0.wrapSpanFormatException$1 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:90224:19)
      at MediaQueryParser0.parse$0 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:87949:19)
      at _EvaluateVisitor__visitMediaQueries_closure2.call$0 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:75186:79)
      at _EvaluateVisitor2._async_evaluate0$_adjustParseError$1$2 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:73345:23)
      at _EvaluateVisitor2._async_evaluate0$_adjustParseError$2 (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:73375:19)
      at /Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart.js:70723:48
      at _wrapJsFunctionForAsync_closure.$protected (/Users/xujingzhu/workspace/race-micro-app/node_modules/sass/sass.dart

**Comment by ClarkXia** [comment]
使用 `@alifd/next` 1.25.46 最新版本
