### ISSUE TITLE
win10;vue admin lite;启动报错

### ISSUE THREAD

**Issue by channg** [alibaba/ice#562]
```
 ERROR  Failed to compile with 8 errors11:23:43
 error  in ./src/App.vue?vue&type=template&id=04c2046b
Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/App.vue?vue&type=template&id=04c2046b 1:0-194 1:0-194
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/pages/Dashboard/Dashboard.vue?vue&type=template&id=12c1125e

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/pages/Dashboard/Dashboard.vue?vue&type=template&id=12c1125e 1:0-212 1:0-212
 @ ./src/pages/Dashboard/Dashboard.vue
 @ ./src/pages/Dashboard/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/pages/NotFound/NotFound.vue?vue&type=template&id=ce1789e4&scoped=true

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/pages/NotFound/NotFound.vue?vue&type=template&id=ce1789e4&scoped=true 1:0-223 1:0-223
 @ ./src/pages/NotFound/NotFound.vue
 @ ./src/pages/NotFound/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
 error  in ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=template&id=c55fda2c&scoped=true

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=template&id=c55fda2c&scoped=true 1:0-221 1:0-221
 @ ./src/layouts/HeaderAsideLayout/Layout.vue
 @ ./src/layouts/HeaderAsideLayout/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/layouts/HeaderAsideLayout/components/NavBar.vue?vue&type=template&id=426a0826&scoped=true

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/layouts/HeaderAsideLayout/components/NavBar.vue?vue&type=template&id=426a0826&scoped=true 1:0-227 1:0-227
 @ ./src/layouts/HeaderAsideLayout/components/NavBar.vue
 @ ./src/layouts/HeaderAsideLayout/components/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue
 @ ./src/layouts/HeaderAsideLayout/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/layouts/HeaderAsideLayout/components/SideBar.vue?vue&type=template&id=49655c14&scoped=true

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/layouts/HeaderAsideLayout/components/SideBar.vue?vue&type=template&id=49655c14&scoped=true 1:0-228 1:0-228
 @ ./src/layouts/HeaderAsideLayout/components/SideBar.vue
 @ ./src/layouts/HeaderAsideLayout/components/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue
 @ ./src/layouts/HeaderAsideLayout/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/layouts/HeaderAsideLayout/components/AppMain.vue?vue&type=template&id=86b92998

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/layouts/HeaderAsideLayout/components/AppMain.vue?vue&type=template&id=86b92998 1:0-216 1:0-216
 @ ./src/layouts/HeaderAsideLayout/components/AppMain.vue
 @ ./src/layouts/HeaderAsideLayout/components/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue
 @ ./src/layouts/HeaderAsideLayout/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
               
 error  in ./src/layouts/HeaderAsideLayout/components/ScrollBar.vue?vue&type=template&id=183c5180&scoped=true

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:7051:13)
    at formatWithCursor (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:10370:12)
    at C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31115:15
    at Object.format (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\prettier\index.js:31134:12)
    at actuallyCompile (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:93:29)
    at compileTemplate (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:26:16)
    at Object.module.exports (C:\Users\xuezhiwen\iceworks-workspace\test\node_modules\vue-loader\lib\loaders\templateLoader.js:42:20)

 @ ./src/layouts/HeaderAsideLayout/components/ScrollBar.vue?vue&type=template&id=183c5180&scoped=true 1:0-230 1:0-230
 @ ./src/layouts/HeaderAsideLayout/components/ScrollBar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/HeaderAsideLayout/components/SideBar.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/components/SideBar.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/components/SideBar.vue
 @ ./src/layouts/HeaderAsideLayout/components/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue?vue&type=script&lang=js
 @ ./src/layouts/HeaderAsideLayout/Layout.vue
 @ ./src/layouts/HeaderAsideLayout/index.js
 @ ./src/routerConfig.js
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by noyobo** [comment]
https://github.com/vuejs/component-compiler-utils/issues/14

**Comment by channg** [comment]
prettier@1.12.0  

添加依赖  解决了这个错误
