### ISSUE TITLE
ice3 ios10.2.1 打开antd-mobile Popup 报错

### ISSUE THREAD

**Issue by gdc1998** [alibaba/ice#5646]
## What is the current behavior? 发生了什么？

ice3 ios10.2.1 打开antd-mobile Popup 报错 Object. values is not a function. (In 'Object.values(c)', 'Object.values' is undefined)

## Any additional comments? 相关环境信息？

- **ice.js Version**：3.0.1
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
配置下兼容性 https://v3.ice.work/docs/guide/basic/config/#%E5%85%BC%E5%AE%B9%E6%80%A7%E9%85%8D%E7%BD%AE

**Comment by gdc1998** [comment]
> 配置下兼容性 https://v3.ice.work/docs/guide/basic/config/#%E5%85%BC%E5%AE%B9%E6%80%A7%E9%85%8D%E7%BD%AE


.browserslistrc 放在根目录报错。放在src或package.json 配置不生效。报错如下
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
    at webpackCompiler (file:///Users/gdc/Desktop/%E9%97%B2%E9%B1%BC/idle-user-join/node_modules/_@ice_app@3.0.1@@ice/app/esm/service/webpackCompiler.js:33:14)
    at async startDevServer (file:///Users/gdc/Desktop/%E9%97%B2%E9%B1%BC/idle-user-join/node_modules/_@ice_app@3.0.1@@ice/app/esm/commands/start.js:103:22)
    at async start (file:///Users/gdc/Desktop/%E9%97%B2%E9%B1%BC/idle-user-join/node_modules/_@ice_app@3.0.1@@ice/app/esm/commands/start.js:34:17)
    at async Object.run (file:///Users/gdc/Desktop/%E9%97%B2%E9%B1%BC/idle-user-join/node_modules/_@ice_app@3.0.1@@ice/app/esm/createService.js:205:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ClarkXia** [comment]
提供下报错复现 demo

**Comment by ClarkXia** [comment]
需要配合 polyfill 配置

**Comment by wh1teYu** [comment]
@gdc1998  怎么最后怎么解决的呢
