### ISSUE TITLE
开启pwa后报错

### ISSUE THREAD

**Issue by aak1247** [alibaba/ice#5657]
build.json 中开启pwa后报错：
deb模式编译成功，浏览器提示：Uncaught SyntaxError: Invalid or unexpected token 报错代码为：
```js
if ('serviceWorker' in navigator && typeof caches !== 'undefined') {
  var workbox = new workbox_window_1.Workbox('\sw.js', {
    scope: '\' // 这里报错
  });
```
icejs build失败，报错：
```bash
ERR! WEBPACK HookWebpackError: Transform failed with 1 error:        
ERR! WEBPACK js/index.js:180:14: ERROR: Unterminated string literal  
ERR! WEBPACK     at makeWebpackError (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:68022:9)
ERR! WEBPACK     at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:51531:12
ERR! WEBPACK     at eval (eval at create (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:40256:10), <anonymous>:85:1)
ERR! WEBPACK     at runMicrotasks (<anonymous>)
ERR! WEBPACK     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR! WEBPACK -- inner error --
ERR! WEBPACK Error: Transform failed with 1 error:
ERR! WEBPACK js/index.js:180:14: ERROR: Unterminated string literal  
ERR! WEBPACK     at failureErrorWithLog (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1624:15)
ERR! WEBPACK     at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1413:29      
ERR! WEBPACK     at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:678:9        
ERR! WEBPACK     at handleIncomingPacket (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:775:9)
ERR! WEBPACK     at Socket.readFromStdout (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:644:7)
ERR! WEBPACK     at Socket.emit (node:events:365:28)
ERR! WEBPACK     at addChunk (node:internal/streams/readable:314:12) 
ERR! WEBPACK     at readableAddChunk (node:internal/streams/readable:289:9)
ERR! WEBPACK     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR! WEBPACK     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
ERR! Transform failed with 1 error:
js/index.js:180:14: ERROR: Unterminated string literal
HookWebpackError: Transform failed with 1 error:
js/index.js:180:14: ERROR: Unterminated string literal
    at makeWebpackError (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:68022:9)
    at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:51531:12
    at eval (eval at create (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\@builder+pack@0.6.5\node_modules\@builder\pack\deps\webpack\bundle5.js:40256:10), <anonymous>:85:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error: Transform failed with 1 error:
js/index.js:180:14: ERROR: Unterminated string literal
    at failureErrorWithLog (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1624:15)
    at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1413:29
    at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)       
    at Socket.Readable.push (node:internal/streams/readable:228:10)  
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)  
caused by plugins in Compilation.hooks.processAssets
Error: Transform failed with 1 error:
js/index.js:180:14: ERROR: Unterminated string literal
    at failureErrorWithLog (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1624:15)
    at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:1413:29
    at D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\Users\aak1247\Repos\hive\puppetry\node_modules\.pnpm\esbuild@0.14.54\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)       
    at Socket.Readable.push (node:internal/streams/readable:228:10)  
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)  
```

- **ice.js Version**：2.6.6
- **build.json Configuration**：
```json
{
  "eslint": true,
  "store": true,
  "pwa": true,
  "dropLogLevel": "log",
  "modeConfig": {
    "dev": {
      "sourceMap": true
    },
    "test": {
      "sourceMap": true
    },
    "uat": {
      "sourceMap": true
    }
  },
  "minify": {
    "type": "esbuild",
    "options": {
      "css": true
    }
  },
  "plugins": [
    [
      "build-plugin-antd",
      {
        "themeConfig": {
          "primary-color": "#2A64EB"
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-icestark",
      {
        "uniqueName": "frameworkJsonp"
      }
    ],
    "./build.plugin.js"
  ],
  "babelPresets": [["@babel/preset-react", { "runtime": "automatic" }]]
}
```
- **Node Version**: 16.0.0
- **Platform**: windows 11

**Comment by aak1247** [comment]
目测是这个未转义的\\导致的问题
