### ISSUE TITLE
2.6.6 jest单元测试中抛出关于axios的异常

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/ice#5744]
## What is the current behavior? 发生了什么？
测试启动的后，用例运行中抛出以下异常
```
TypeError: Cannot read properties of undefined (reading 'create')

      at Object.<anonymous> (E:/repos/serverfrontend/.ice/plugins/request/createAxiosInstance.ts:7:18)
      at Object.<anonymous> (E:/repos/serverfrontend/.ice/plugins/request/request.ts:3:1)
      at Object.<anonymous> (E:/repos/serverfrontend/.ice/index.ts:7:1)
      at Object.<anonymous> (node_modules/aria-query/lib/etc/roles/ariaDpubRoles.js:35:45)
      at Object.<anonymous> (node_modules/aria-query/lib/rolesMap.js:9:45)
      at Object.<anonymous> (node_modules/aria-query/lib/index.js:9:40)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/role-helpers.js:19:18)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/suggestions.js:16:20)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/query-helpers.js:16:20)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/queries/all-utils.js:33:21)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/queries/label-text.js:14:17)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/queries/index.js:7:18)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/get-queries-for-element.js:8:46)
      at Object.<anonymous> (node_modules/@testing-library/dom/dist/index.js:61:29)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/pure.js:33:12)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:7:13)
      at Object.<anonymous> (E:/repos/serverfrontend/src/pages/Workflow/tests/workflow.spec.tsx:4:1)
```
定位到文件 .ice/plugins/request/createAxiosInstance.ts:7:18，代码如下：
```
const axiosInstance = {
  default: axios.create(DEFAULE_CONFIG)
};
```
结合异常信息感觉应该是axios导入没有成功

jest.config.js配置如下
```
module.exports = {
  preset: 'ts-jest',
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  clearMocks: true,
  // Indicates whether the coverage information should be collected while executing the test
  collectCoverage: false,
  coverageDirectory: "coverage",
  moduleNameMapper: {
    'ice': '<rootDir>/.ice',
  },
  // Use this configuration option to add custom reporters to Jest
  reporters: ['default', 'jest-junit'],
  // The paths to modules that run some code to configure or set up the testing environment before each test
  setupFiles: ['jest-localstorage-mock'],
  // A list of paths to modules that run some code to configure or set up the testing framework before each test
  setupFilesAfterEnv: [ './jest.setup.js'],
  testEnvironment: "jsdom",
  testMatch: ['**.spec.ts','**.spec.tsx'],
  globals: {
    'ts-jest': {
      diagnostics: false,
    },
  },
};
```
tsconfig.json配置如下：
```
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build",
    "module": "esnext",
    "target": "es6",
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "rootDir": "./",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "types": ["node", "jest"],
    "paths": {
      "@/*": ["./src/*"],
      "ice": [".ice/index.ts"],
      "ice/*": [".ice/pages/*"]
    },
    "esModuleInterop": true
  },
  "include": ["src", ".ice"],
  "exclude": ["node_modules", "build", "public"]
}
```
## What is the expected behavior? 期望的结果是什么？
期望用例能正常启动
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
```
{
  "outputDir": "dist",
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}
```
- **Node Version**:
- **Platform**: win 10

**Comment by ClarkXia** [comment]
能否提供一个简单的复现 demo

**Comment by HengzheLi** [comment]
https://codesandbox.io/s/kind-lake-8u3mt2

下载后直接运行 npm run test
```
TypeError: Cannot read properties of undefined (reading 'create')

       5 |
       6 | const axiosInstance = {
    >  7 |   default: axios.create(DEFAULE_CONFIG)
         |                  ^
       8 | };
       9 |
      10 | /**

      at Object.<anonymous> (.ice/plugins/request/createAxiosInstance.ts:7:18)
      at Object.<anonymous> (.ice/plugins/request/request.ts:3:1)
      at Object.<anonymous> (.ice/index.ts:6:1)
      at Object.<anonymous> (src/test.spec.tsx:5:1)
```

**Comment by HengzheLi** [comment]
有什么方向我可以先入手修改的吗

**Comment by HengzheLi** [comment]
@luhc228 有什么发现吗
