### ISSUE TITLE
启动报错，import './env.server'; SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by frogo** [alibaba/ice#6323]
### Describe the bug

`
PS D:\iflytek\ZFW_PROJECT\TEMP-BRANCH\ice-app> npm run start

> @ice/lite-scaffold@1.1.0 start
> ice start

webpack 5.80.0 compiled successfully in 4367 ms
                                                                                                                                                                               10:36:38
 Starting the development server at:

    - Local  : http://localhost:3000/
    - Network: http://192.168.160.1:3000/

D:\iflytek\ZFW_PROJECT\TEMP-BRANCH\ice-app\.ice\entry.server.ts:1
import './env.server';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInThisContext (node:vm:313:10)
    at ServerRunner.requestModule (file:///D:/iflytek/ZFW_PROJECT/TEMP-BRANCH/ice-app/node_modules/@ice/app/esm/service/Runner.js:173:23)
    at async ServerRunner.cachedRequest (file:///D:/iflytek/ZFW_PROJECT/TEMP-BRANCH/ice-app/node_modules/@ice/app/esm/service/Runner.js:44:20)
    at async ServerRunner.run (file:///D:/iflytek/ZFW_PROJECT/TEMP-BRANCH/ice-app/node_modules/@ice/app/esm/service/Runner.js:33:16)
    at async middleware (file:///D:/iflytek/ZFW_PROJECT/TEMP-BRANCH/ice-app/node_modules/@ice/app/esm/middlewares/renderMiddleware.js:18:34)
PS D:\iflytek\ZFW_PROJECT\TEMP-BRANCH\ice-app> 
`

### Expected behavior

能够访问3000端口

### Version of ice.js

3.0.0

**Comment by ClarkXia** [comment]
node 版本是多少

**Comment by frogo** [comment]
> node 版本是多少

16.18.0

**Comment by ClarkXia** [comment]
目前没法复现你这个场景，可以先将 ice.config.mts 中的 server 配置项设置成 `server: { format: 'cjs', bundle: true }` 试下

**Comment by frogo** [comment]
> 目前没法复现你这个场景，可以先将 ice.config.mts 中的 server 配置项设置成 `server: { format: 'cjs', bundle: true }` 试下

感谢大佬解答，我使用pnpm，正常了。不报错了。
