### ISSUE TITLE
ice3.0.0引入antd后报错，但页面渲染正常

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6462]
### Describe the bug

 ERROR  Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'   

  at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
  at new NodeError (node:internal/errors:387:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1017:11)        
  at defaultResolve (node:internal/modules/esm/resolve:1097:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ESMLoader.import (node:internal/modules/esm/loader:521:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)       
  at ServerRunner.interopedImport (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:188:32)
  at ServerRunner.requestModule (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:107:40)
  at ServerRunner.cachedRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at ServerRunner.dependencyRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at src\pages\layout.tsx:4:26
  at ServerRunner.requestModule (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at ServerRunner.cachedRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at ServerRunner.dependencyRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at lazy (.ice\routes.tsx:10:41)
  at loadRouteModule (/D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (/D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (/D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:193:30)
  at Module.renderToResponse (/D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:78:20)

 ERROR  Cannot read properties of undefined (reading 'Button')            10:54:03  

  at src\pages\layout.tsx:5:33
  at ServerRunner.requestModule (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at ServerRunner.cachedRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at ServerRunner.dependencyRequest (/D:/study/ice-app/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at lazy (.ice\routes.tsx:10:41)
  at loadRouteModule (/D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (/D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (/D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:193:30)
  at Module.renderToResponse (/D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:78:20)

Failed to load route module: layout.
TypeError: Cannot destructure property 'dataLoader' of 'options.module' as it is undefined.
    at createRouteLoader (file:///D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:79:13)
    at lazy (D:\study\ice-app\.ice\routes.tsx:18:29)
    at loadRouteModule (file:///D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:27:29)
    at loadRouteModules (file:///D:/study/ice-app/node_modules/@ice/runtime/esm/routes.js:39:29)
    at doRender (file:///D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:193:30)
    at Module.renderToResponse (file:///D:/study/ice-app/node_modules/@ice/runtime/esm/runServerApp.js:78:20)

### Expected behavior

控制台不要报错

### Version of ice.js

3.2.9
### Content of build.json or ice.config.mts

import { defineConfig } from '@ice/app';
import antd from '@ice/plugin-antd';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
  plugins: [
    antd({
      importStyle: true,
    }),
  ],
}));
### Additional context

node 版本：16.18.0 + windows10

**Comment by ClarkXia** [comment]
windows 下的问题，可以先关闭 onDemand

**Comment by honeysweetful** [comment]
> windows 下的问题，可以先关闭 onDemand

有用，谢谢
