### ISSUE TITLE
创建的应用启动不了

### ISSUE THREAD

**Issue by chen-chunk** [alibaba/ice#6489]
### Describe the bug

npm create ice ice-app
模板：Web Lite Scaffold

cd ice-app
npm install
npm start

按这个流程操作启动不了

### Expected behavior

(base) PS C:\test> node -v
v16.19.1
(base) PS C:\test> npm create ice ice-app
create-ice version: 1.9.0
create-ice args ice-app undefined
? Please select a template Web Lite Scaffold
download tarballURL https://registry.npmmirror.com/@ice/lite-scaffold/-/lite-scaffold-1.2.0.tgz
✔ download npm tarball successfully.

Initialize project successfully.

Starts the development server.

    cd ice-app
    npm install
    npm start

We have prepared develop toolkit for you.
See: https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks

(base) PS C:\test> cd .\ice-app\
(base) PS C:\test\ice-app> npm i

added 863 packages in 3m
(base) PS C:\test\ice-app> npm run start

> @ice/lite-scaffold@1.2.0 start
> ice start --speedup

file:///C:/test/ice-app/node_modules/@ice/rspack-config/esm/splitChunks.js:36
    const frameworkTest = new RegExp(frameworkPaths.join('|'));
                          ^

SyntaxError: Invalid regular expression: /C:\test\ice-app\node_modules\react\|C:\test\ice-app\node_modules\loose-envify\|C:\test\ice-app\node_modules\js-tokens\|C:\test\ice-app\node_modules\react-dom\|C:\test\ice-app\node_modules\scheduler\|C:\test\ice-app\node_modules\react-router\|C:\test\ice-app\node_modules\@remix-run\router\|C:\test\ice-app\node_modules\react-router-dom\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at getChunksStrategy (file:///C:/test/ice-app/node_modules/@ice/rspack-config/esm/splitChunks.js:36:27)
    at getSplitChunks (file:///C:/test/ice-app/node_modules/@ice/rspack-config/esm/splitChunks.js:81:12)
    at getConfig (file:///C:/test/ice-app/node_modules/@ice/rspack-config/esm/index.js:75:19)
    at file:///C:/test/ice-app/node_modules/@ice/app/esm/bundler/rspack/getConfig.js:42:16
    at Array.map (<anonymous>)
    at getConfig (file:///C:/test/ice-app/node_modules/@ice/app/esm/bundler/rspack/getConfig.js:40:24)
    at bundler (file:///C:/test/ice-app/node_modules/@ice/app/esm/bundler/rspack/index.js:8:33)
    at Object.run (file:///C:/test/ice-app/node_modules/@ice/app/esm/createService.js:339:33)
    at Command.<anonymous> (file:///C:/test/ice-app/node_modules/@ice/app/bin/ice-cli.mjs:68:15)
(base) PS C:\test\ice-app>

### Version of ice.js

3.3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
}));
```

**Comment by ClarkXia** [comment]
先删除 pakage.json 中的 —speedup 参数，我们尽快修复下 win32 下的适配

**Comment by chen-chunk** [comment]
可以了，多谢
