### ISSUE TITLE
Buffer Recursion in resolving

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/ice#6603]
> ```js
> require.resolve('buffer/')
> ```

```js
import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
  alias: {
    buffer: 'buffer/',
  },
}));

启动时报以下错误
···
Module not found: Error: Recursion in resolving
Stack:
  resolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer
  parsedResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer module
  describedResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer module
  rawResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer module
  internalResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer/ module
  parsedResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer directory module
  describedResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer directory module
  rawResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer directory module
  internalResolve: (D:\projects\test\test\ice-app-1023\src\pages) buffer/ directory module

···
```

_Originally posted by @lilithyang2018 in https://github.com/alibaba/ice/issues/6597#issuecomment-1774521630_

**Comment by lilithyang2018** [comment]
这样配置 似乎可行
```js
webpack: (config, ctx) => {
        config.resolve = {
            ...config.resolve,
            fallback: {
                ...(config.resolve?.fallback || {}),
                Buffer: 'buffer/',
            },
        };
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        config.plugins?.push(new ProvidePlugin({
            Buffer: ['buffer', 'Buffer'],
        }));
        return config;
    },
```
![buffer](https://github.com/alibaba/ice/assets/39897706/0565c1e3-0d77-4eaf-9e73-2967f0670f64)

**Comment by lilithyang2018** [comment]
但是对第三方库无效
![buffer-error](https://github.com/alibaba/ice/assets/39897706/3e0250ce-b754-4996-9f44-4ae893f050eb)

**Comment by lilithyang2018** [comment]
```js
Uncaught (in promise) Error: Error during encryption. Original error: ReferenceError: Buffer is not defined
    at push../node_modules/@learntheropes/node-rsa/src/NodeRSA.js.module.exports.NodeRSA.$$encryptKey (NodeRSA.js:284:1)
    at push../node_modules/@learntheropes/node-rsa/src/NodeRSA.js.module.exports.NodeRSA.encrypt (NodeRSA.js:239:1)
    at encrypt (RsaUtils.ts:7:1)
    at encodePassword (RsaUtils.ts:10:1)
    at index.tsx:64:1
    at step (tslib.es6.mjs:147:1)
    at Object.next (tslib.es6.mjs:128:1)
    at asyncGeneratorStep (_async_to_generator.js:3:1)
    at _next (_async_to_generator.js:20:1)
```
并不管用，再试试umijs

**Comment by lilithyang2018** [comment]
@ClarkXia  umijs那边的处理逻辑
```js
export async function addNodePolyfill(opts: IOpts) {
  const { config } = opts;
  const nodeLibs = require('node-libs-browser');

  config.plugin('node-polyfill-provider').use(ProvidePlugin, [
    {
      Buffer: ['buffer', 'Buffer'],
      process: nodeLibs['process'],
    },
  ]);

  config.resolve.fallback.merge({
    ...Object.keys(nodeLibs).reduce<Record<string, boolean>>((memo, key) => {
      if (nodeLibs[key]) {
        memo[key] = nodeLibs[key];
      } else {
        memo[key] = false;
      }
      return memo;
    }, {}),
    http: false,
    https: false,
  });
}
```
但是似乎在ice这边不管用, 能不能把这部分也集成到ice的内置webpack配置里面呢？
