### ISSUE TITLE
使用yarn安装依赖无法启动项目

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6605]
### Describe the bug

问题一：我在使用yarn安装依赖以后，无法启动项目，会提示报错。但是使用pnpm或者npm就不存在这个问题。

错误截图
![image](https://github.com/alibaba/ice/assets/50658231/dd7e5bc8-25c3-42ea-ac1c-66149073e1a5)
```sh
/usr/local/bin/npm run start

> cbi_frontend@1.2.0 start
> ice start --speedup

node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module '@ice/css-modules-hash-darwin-arm64'
Require stack:
- /Users/qiuqiu/development/code/CBI_Frontend/node_modules/@ice/css-modules-hash/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at mod._resolveFilename (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/@ice/app/esm/requireHook.js:51:32)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/qiuqiu/development/code/CBI_Frontend/node_modules/@ice/css-modules-hash/index.js:141:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/qiuqiu/development/code/CBI_Frontend/node_modules/@ice/css-modules-hash/index.js'
  ]
}

Node.js v18.17.1

进程已结束，退出代码为 1


```
---
问题二：在使用pnpm或者npm正常启动项目，会出现几个`error`错误但是项目能正常使用。
```sh
/usr/local/bin/npm run start

> cbi_frontend@1.2.0 start
> ice start --speedup

✔ web compiled successfully in 3734 ms                                                                                                                                                         15:36:19
                                                                                                                                                                                               15:36:19
 Starting the development server at:

    - Local  : http://localhost:3000/
    - Network: http://192.168.1.5:3000/


 ERROR  styled is not a function                                                                                                                                                               15:36:27

  at src/layouts/ActionArea/style.ts:3:27
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at src/layouts/ActionArea/index.tsx:18:26
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at src/pages/layout.tsx:8:26
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at lazy (.ice/routes.tsx:10:41)
  at loadRouteModule (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)


 ERROR  Cannot read properties of undefined (reading 'ValidityPeriodBox')                                                                                                                      15:36:27

  at src/layouts/ActionArea/index.tsx:19:44
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at src/pages/layout.tsx:8:26
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at lazy (.ice/routes.tsx:10:41)
  at loadRouteModule (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
  at Module.renderToResponse (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)


 ERROR  Cannot read properties of undefined (reading 'default')                                                                                                                                15:36:27

  at src/pages/layout.tsx:9:37
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at lazy (.ice/routes.tsx:10:41)
  at loadRouteModule (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
  at Module.renderToResponse (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)

Failed to load route module: layout.
TypeError: Cannot destructure property 'dataLoader' of 'options.module' as it is undefined.
    at createRouteLoader (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:79:13)
    at lazy (/Users/qiuqiu/development/code/CBI_Frontend/.ice/routes.tsx:18:29)
    at loadRouteModule (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
    at loadRouteModules (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)
Warning: render server entry error, downgrade to csr. TypeError: Cannot destructure property 'loader' of 'routeModules[routeId]' as it is undefined.
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:210:21)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)

 ERROR  Cannot read properties of undefined (reading 'default')                                                                                                                                15:36:27

  at src/pages/layout.tsx:9:37
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at lazy (.ice/routes.tsx:10:41)
  at loadRouteModule (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
  at Module.renderToResponse (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)

Failed to load route module: layout.
TypeError: Cannot destructure property 'dataLoader' of 'options.module' as it is undefined.
    at createRouteLoader (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:79:13)
    at lazy (/Users/qiuqiu/development/code/CBI_Frontend/.ice/routes.tsx:18:29)
    at loadRouteModule (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
    at loadRouteModules (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)
Warning: render server entry error, downgrade to csr. TypeError: Cannot destructure property 'loader' of 'routeModules[routeId]' as it is undefined.
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:210:21)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)

 ERROR  Cannot read properties of undefined (reading 'default')                                                                                                                                15:36:28

  at src/pages/layout.tsx:9:37
  at ServerRunner.requestModule (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:179:9)
  at ServerRunner.cachedRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:45:20)
  at ServerRunner.dependencyRequest (node_modules/.pnpm/@ice+app@3.3.5_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@ice/app/esm/service/Runner.js:90:20)
  at lazy (.ice/routes.tsx:10:41)
  at loadRouteModule (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
  at loadRouteModules (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
  at doRender (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
  at Module.renderToResponse (node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)

Failed to load route module: layout.
TypeError: Cannot destructure property 'dataLoader' of 'options.module' as it is undefined.
    at createRouteLoader (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:79:13)
    at lazy (/Users/qiuqiu/development/code/CBI_Frontend/.ice/routes.tsx:18:29)
    at loadRouteModule (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:27:29)
    at loadRouteModules (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/routes.js:39:29)
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:207:30)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)
Warning: render server entry error, downgrade to csr. TypeError: Cannot destructure property 'loader' of 'routeModules[routeId]' as it is undefined.
    at doRender (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:210:21)
    at Module.renderToResponse (file:///Users/qiuqiu/development/code/CBI_Frontend/node_modules/.pnpm/@ice+runtime@1.3.2_react-dom@18.2.0_react@18.2.0/node_modules/@ice/runtime/esm/runServerApp.js:79:20)
```
报错的部分代码，
```tsx
import { styled } from '@mui/material/styles';

export const ValidityPeriodBox = styled('div')({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  '.title': {
    color: 'gold',
  },
  'validity-period': {
    color: 'white',
  },
});

```

### Expected behavior

能够使用yarn安装依赖后成功启动，并且没有报错信息。

### Version of ice.js

v3.3.0

### Content of build.json or ice.config.mts

```TypeScript
import {defineConfig} from '@ice/app';
import store from '@ice/plugin-store';
import request from '@ice/plugin-request';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
    minify,
    plugins: [store(), request()],
    server: {
        onDemand: true,
        format: 'esm',
    },
    routes: {
        ignoreFiles: ['widgets', 'components']
    }
}));
```

**Comment by oneQiu** [comment]
问题二我在vite有查到类似的，但是我不确定是否是同类型问题。

**Comment by ClarkXia** [comment]
第一个问题是 @ice/css-modules-hash-darwin-arm64 这个包没有正确被安装
第二个问题有具体错误栈，可以先定位下什么代码源引起的，也可以提供在这个 issue 下供复现

**Comment by ClarkXia** [comment]
推荐先用最新版本 再试下，如果还是有问题，可以提供复现 demo
