### ISSUE TITLE
使用最新版 react-router-dom 的 useNavigation 时报错：must be used within a data router

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/ice#6624]
### Describe the bug

为解决多次渲染问题(#6461 )，在项目中单独安装了 `react-router-dom `并使用了其中的 `useNavigation`。在近期升级到最新版 `react-router-dom` 时，报以下错误。
```
Uncaught Error: useNavigation must be used within a data router.  See https://reactrouter.com/routers/picking-a-router.
    at invariant (router.js:241:1)
    at useDataRouterState (index.js:617:1)
    at useNavigation (index.js:646:1)
    at HomePage (index.tsx:4:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```
然而我看了：https://reactrouter.com/routers/picking-a-router
也没看懂，是不是和框架有点关系？

### Expected behavior

不报错

### Version of ice.js

3.2.10

#### 复现
https://codesandbox.io/p/github/aspirantzhang/ice-test/draft/recursing-northcutt?file=%2Fsrc%2Fpages%2Findex.tsx%3A10%2C11
请关注 Console

#### 临时处理方案
将 react-router-dom 降级到 v6.14.2 即可

**Comment by ClarkXia** [comment]
项目中不建议再独立安装 react-router 相关依赖，报错原因是多个 react-router-dom 版本导致的实例问题。useNavigation 可以直接从 ice 里面导出，如果存在其他 API 诉求，可以 PR 和 issue 的方式反馈给我们。近期我们也会考虑升级 react-router 相关依赖版本

**Comment by aspirantzhang** [comment]
@ClarkXia ice 里目前可以导出 useNavigate，但没有导出 useNavigation，下次升级的时候搞一下吧。
