### ISSUE TITLE
启动项目后进入登录页面就报csr的错，但不影响项目跑动

### ISSUE THREAD

**Issue by jackHuang-123** [alibaba/ice#6983]
### Describe the bug

ERROR  Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'              11:15:09  

  at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
  at new NodeError (node:internal/errors:399:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
  at defaultResolve (node:internal/modules/esm/resolve:1135:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ESMLoader.import (node:internal/modules/esm/loader:525:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at ServerRunner.interopedImport (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:188:32)
  at ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:107:40)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\login\index.tsx:5:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'Message')                                                                                                                       11:15:09  

  at src\pages\login\index.tsx:6:34
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

PipeToResponse error.
Error: Route "login/index" has no component! Please go add a `default` export in the route module file.
If you were trying to navigate or submit to a resource route, use `<a>` instead of `<Link>` or `<Form reloadDocument>`.
    at RouteComponent (file:///D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:126:19)
    at renderWithHooks (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5797:15)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
PipeToResponse onShellError, downgrade to CSR.
Error: Route "login/index" has no component! Please go add a `default` export in the route module file.
If you were trying to navigate or submit to a resource route, use `<a>` instead of `<Link>` or `<Form reloadDocument>`.
    at RouteComponent (file:///D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:126:19)
    at renderWithHooks (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5797:15)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)

 ERROR  Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'              11:15:37  

  at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
  at new NodeError (node:internal/errors:399:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
  at defaultResolve (node:internal/modules/esm/resolve:1135:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ESMLoader.import (node:internal/modules/esm/loader:525:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at ServerRunner.interopedImport (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:188:32)
  at ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:107:40)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\login\index.tsx:5:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'Avatar')                                                                                                                        11:15:37  

  at src\components\HeaderAvatar\index.tsx:8:33
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\layout\Header\index.tsx:8:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\layout\index.tsx:9:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'default')                                                                                                                       11:15:37  

  at src\pages\layout\Header\index.tsx:9:39
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\layout\index.tsx:9:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'default')                                                                                                                       11:15:37  

  at src\pages\layout\index.tsx:10:33
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'              11:15:37  

  at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
  at new NodeError (node:internal/errors:399:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
  at defaultResolve (node:internal/modules/esm/resolve:1135:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ESMLoader.import (node:internal/modules/esm/loader:525:22)
  at importModuleDynamically (node:internal/modules/esm/translators:110:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at ServerRunner.interopedImport (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:188:32)
  at ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:107:40)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\login\index.tsx:5:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'Form')                                                                                                                          11:15:37  

  at src\hooks\useTableData copy.tsx:7:31
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async src\pages\stock\inventoryPlan\index.tsx:6:26
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

 ERROR  Cannot read properties of undefined (reading 'useTableData')                                                                                                                  11:15:37  

  at src\pages\stock\inventoryPlan\index.tsx:7:39
  at async ServerRunner.requestModule (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:178:9)
  at async ServerRunner.cachedRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:44:20)
  at async ServerRunner.dependencyRequest (/D:/project/tets/factoryclient/node_modules/@ice/app/esm/service/Runner.js:89:20)
  at async loadRouteModule (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:25:29)
  at async loadRouteModules (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:37:29)
  at async doRender (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:166:30)
  at async Module.renderToResponse (/D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/runServerApp.js:71:20)

PipeToResponse error.
Error: Route "layout/index" has no component! Please go add a `default` export in the route module file.
If you were trying to navigate or submit to a resource route, use `<a>` instead of `<Link>` or `<Form reloadDocument>`.
    at RouteComponent (file:///D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:126:19)
    at renderWithHooks (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5797:15)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
PipeToResponse onShellError, downgrade to CSR.
Error: Route "layout/index" has no component! Please go add a `default` export in the route module file.
If you were trying to navigate or submit to a resource route, use `<a>` instead of `<Link>` or `<Form reloadDocument>`.
    at RouteComponent (file:///D:/project/tets/factoryclient/node_modules/@ice/runtime/esm/routes.js:126:19)
    at renderWithHooks (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5797:15)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderContextProvider (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5986:3)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6142:14)
    at renderIndeterminateComponent (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:5851:7)
    at renderElement (D:\project\tets\factoryclient\node_modules\react-dom\cjs\react-dom-server.node.development.js:6012:7)
其中的这些Message都是正常引入的，还有login的暴露引入也是正常引入
![image](https://github.com/user-attachments/assets/2dd3e892-37da-448a-ad21-bef3417c437c)

### Expected behavior

希望不报错

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
csr 项目关闭 ssg，在用户配置上开启 `ssg: false`

**Comment by jackHuang-123** [comment]
> csr 项目关闭 ssg，在用户配置上开启`ssg: false`

感谢大佬，已解决
