### ISSUE TITLE
生成页面失败

### ISSUE THREAD

**Issue by AndyTian** [alibaba/ice#726]
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at module.exports (C:\Users\lenovo\AppData\Local\Programs\iceworks-desktop\resources\app\main\utils\npmRequest.js:1:367)
    at Promise (C:\Users\lenovo\AppData\Local\Programs\iceworks-desktop\resources\app\main\template\utils\getTarballURLBySource.js:1:209)
    at new Promise ()
    at Object.module.exports [as getTarballURLBySource] (C:\Users\lenovo\AppData\Local\Programs\iceworks-desktop\resources\app\main\template\utils\getTarballURLBySource.js:1:173)
    at Object.module.exports [as createPage] (C:\Users\lenovo\AppData\Local\Programs\iceworks-desktop\resources\app\main\scaffolder\lib\createPage.js:1:1657)
    at

**Comment by noyobo** [comment]
fixed v2.5.1
