### ISSUE TITLE
Could not call remote function 'spawn'

### ISSUE THREAD

**Issue by lgscofield** [alibaba/ice#783]
## 环境信息

- 操作系统：win 10
- Iceworks 版本： 最新版，2018年8月6日更新到最新版

## 错误信息

1. 创建Antular模板
2. 报错信息：
Could not call remote function 'spawn'. Check that the function signature is correct. Underlying error: Unable to start terminal process: CreateProcess failed
Error: Could not call remote function 'spawn'. Check that the function signature is correct. Underlying error: Unable to start terminal process: CreateProcess failed
    at callFunction (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter. (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents. (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
Error: Could not call remote function 'spawn'. Check that the function signature is correct. Underlying error: Unable to start terminal process: CreateProcess failed
Error: Could not call remote function 'spawn'. Check that the function signature is correct. Underlying error: Unable to start terminal process: CreateProcess failed
    at callFunction (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter. (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents. (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\renderer\api\remote.js:213:28)
    at Object.remoteMemberFunction (C:\Users\ligh\AppData\Local\Programs\iceworks-desktop\resources\electron.asar\renderer\api\remote.js:113:16)
    at Terms.newPty (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/index.js:11402:28)
    at Terms._new (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/index.js:11427:16)
    at ProjectTerminal.createTerm (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/index.js:58606:35)
    at ProjectTerminal.componentDidMount (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/index.js:58593:12)
    at commitLifeCycles (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/commons.js:30703:92)
    at R (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/commons.js:30729:7)
    at G (file:///C:/Users/ligh/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/commons.js:30726:349)

**Comment by noyobo** [comment]
杀毒软件添加 iceworks 白名单后，重装后重试下。

**Comment by noyobo** [comment]
或者尝试使用管理员权限运行。
