### ISSUE TITLE
预览新建页面出现报错 Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by zhusonglai** [alibaba/ice#830]
## 环境信息

- 操作系统：mac os 10.11.6
- Iceworks 版本： 2.5.2

## 问题描述
预览新建页面出现报错 Cannot read property 'some' of undefined

如果一个完全新建一个新项目，可以预览与新建，在用iceworks建的之前的项目，预览与打开，就报错。

## 错误信息
Cannot read property 'some' of undefined

Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at VariableDeclarator.node.init.elements.some.oe (/Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:54:34)
    at Array.some ()
    at VariableDeclarator (/Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:53:48)
    at NodePath._call (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Applications/Iceworks.app/Contents/Resources/app/node_modules/babel-traverse/lib/index.js:79:12)
    at /Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:46:5
    at Generator.next ()
    at step (/Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:3:221)
    at _next (/Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:3:409)
    at /Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:3:477
    at new Promise ()
    at /Applications/Iceworks.app/Contents/Resources/app/node_modules/@ali/iceworks-scaffolder/lib/menu/appendMenu.js:3:97

**Comment by noyobo** [comment]
之前的项目是也是用 iceworks 创建的吗
