### ISSUE TITLE
编译下载不到chrome-win.zip

### ISSUE THREAD

**Issue by wylgng** [alibaba/ice#969]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.9.0

## 问题描述
npm install 出错
https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/594312/chrome-win.zip 地址404

## 错误信息

> puppeteer@1.9.0 install D:\dev\project\Electron\ice\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/594312/chrome-win.zip
    at response (D:\dev\project\Electron\ice\node_modules\puppeteer\lib\BrowserFetcher.js:233:21)
    at ClientRequest.requestCallback (D:\dev\project\Electron\ice\node_modules\puppeteer\lib\BrowserFetcher.js:289:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

**Comment by noyobo** [comment]
网络问题，可使用 淘宝镜像 或者 cnpm 安装。
