### ISSUE TITLE
Fusion私有物料源模板无法使用

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#976]
## 环境信息

- 操作系统：
Mac OS
- Iceworks 版本： 
2.10.0

## 问题描述

使用私有物料源的模板出错

复现步骤: 
1. 新增私有物料源 https://alifd.alicdn.com/assets/db-daily.json
2. 刷新以后任选一个模板 并使用该模板
3. 点击无反应,后台报错

## 错误信息
```
Error: Could not call remote function 'add'. Check that the function signature is correct. Underlying error: Cannot read property 'ice-scripts' of undefined
Error: Could not call remote function 'add'. Check that the function signature is correct. Underlying error: Cannot read property 'ice-scripts' of undefined
    at callFunction (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Iceworks.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/Iceworks.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/Iceworks.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/Applications/Iceworks.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:16)
    at file:///Applications/Iceworks.app/Contents/Resources/app/renderer/index.js:27547:51
    at new Promise (<anonymous>)
    at Scaffold.create (file:///Applications/Iceworks.app/Contents/Resources/app/renderer/index.js:27546:14)
    at $ (file:///Applications/Iceworks.app/Contents/Resources/app/renderer/mobx.umd.min.js:1:7238)
    at Scaffold.n (file:///Applications/Iceworks.app/Contents/Resources/app/renderer/mobx.umd.min.js:1:7006)
    at file:///Applications/Iceworks.app/Contents/Resources/app/renderer/home.js:3719:41
    at <anonymous>
```

**Comment by noyobo** [comment]
```diff
if (isCustomScaffold) {
    needCreateDefflow = isAlibaba;
    layoutConfig.directory = targetPath;
    layoutConfig.name = projectName;
    fn = templateBuilderUtils.generateTemplate(layoutConfig);
  } else {
+    const scaffoldDevDeps = scaffold && scaffold.devDependencies;
    needCreateDefflow = isAlibaba && scaffoldDevDeps['ice-scripts'];
    fn = template.createProject(getOptions(_options), afterCreateRequest);
  }
```

这行引起的
